// HP ELF-träning: egna engelska övningstexter i högskoleprovets stil (inga UHR-texter).
// Samma format som LÄS, så LÄS-träningens vy kan återanvändas.
import type { HpLasText, HpLasOption } from "./hp-las";
import { HP_ELF_TEXTS_HP } from "./hp-elf-hp";

const o = (text: string, why: string): HpLasOption => ({ text, why });

const HP_ELF_TEXTS_BAS: HpLasText[] = [
  {
    id: "elf-tulpan",
    title: "The Tulip Story We Like to Tell",
    topic: "historia",
    paragraphs: [
      "Tulip mania is the favourite cautionary tale of popular economics. In the 1630s, the story goes, the Dutch were seized by a collective madness, swapping a single bulb for the price of a canal house until the market collapsed and thousands of families were ruined. The tale has been retold in textbooks, newspaper columns and investment seminars for nearly two centuries, usually as proof that crowds are irrational and that every boom must end in a bust.",
      "Historians who return to the archives find a far less dramatic picture. Surviving records show few signs of mass bankruptcy, and no known trader appears to have been destroyed by the fall in prices. Much of the vivid detail comes from pamphlets written by moralists, who had every reason to portray speculation as a sin and its victims as fools. Most deals in the winter of 1636 were futures contracts, and when prices dropped, many buyers simply declined to honour them; the courts, unsure how to treat such wagers, let the matter fade.",
      "None of this means that the prices were sensible. Some rare bulbs did sell for sums that startled contemporaries, and the episode was undoubtedly a bubble of a modest kind. But its effects on the wider Dutch economy seem to have been slight, which makes it a poor example of a catastrophe. A mania, it turns out, need not end in a crash, and a crash need not ruin a nation.",
      "The real lesson may concern us rather than the Dutch. We keep retelling the story because it flatters us, assuring each generation that it would have known better than its ancestors. A tale that comforts so reliably deserves, if nothing else, a degree of suspicion from those who repeat it. History, after all, is rarely as tidy as the lessons we draw from it.",
    ],
    questions: [
      {
        id: "elf-tulpan-1",
        type: "huvudtanke",
        prompt: "Which statement best summarises the main point of the text?",
        options: [
          o("Tulip mania is a well-documented example of economic ruin caused by irrational crowds.", "Motsatsen. Det är just den traditionella bilden (stycke 1) som texten ifrågasätter när historiker 'returns to the archives' och inte hittar massruin."),
          o("The usual account of tulip mania exaggerates its consequences, and its popularity says something about those who retell it.", "Rätt. Texten går från myten (stycke 1) via arkivfynden (2) och den lilla bubblan (3) till slutpoängen att historien smickrar oss (4)."),
          o("Dutch courts were responsible for ending the tulip market.", "Bara en liten detalj och en överdrift. Stycke 2 säger att domstolarna 'let the matter fade', inte att de avslutade marknaden."),
          o("Speculative bubbles never occur in real markets.", "För starkt och fel. Stycke 3 säger uttryckligen att det 'undoubtedly' var en bubbla, om än en måttlig. Texten förnekar inte bubblor."),
        ],
        correct: 1,
        paragraph: 1,
      },
      {
        id: "elf-tulpan-2",
        type: "detalj",
        prompt: "According to the text, why did many buyers avoid financial loss when prices fell?",
        options: [
          o("They had sold their bulbs shortly before prices collapsed.", "Står inte i texten. Inget sägs om att köparna hann sälja i tid."),
          o("They had been warned in advance by the pamphlets.", "Förvrängning. Pamfletterna nämns i stycke 2 som källa till överdrifterna, skrivna av moralister, inte som varningar till köpare."),
          o("The courts compensated them for their losses.", "Motsatsen. Domstolarna 'let the matter fade', alltså hände ingenting; ingen ersättning nämns."),
          o("Their contracts were futures agreements, which many simply refused to honour.", "Rätt. Stycke 2: 'futures contracts, and ... many buyers simply declined to honour them'."),
        ],
        correct: 3,
        paragraph: 1,
      },
      {
        id: "elf-tulpan-3",
        type: "syfte",
        prompt: "What is the author's attitude to the traditional tulip story?",
        options: [
          o("Sceptical of its accuracy, yet willing to accept that some speculation took place.", "Rätt. Skepsis mot dramatiken (stycke 2) men 'undoubtedly a bubble of a modest kind' (stycke 3)."),
          o("Admiring of its value as a warning to investors.", "Fel ton. Författaren kallar den 'a tale that comforts' och ber oss misstro den (stycke 4), inte hylla den."),
          o("Convinced that moralists invented the whole story.", "För starkt. Stycke 2 säger att 'much of the vivid detail' kommer från moralister, inte att allt är påhittat; det fanns faktiskt en bubbla."),
          o("Indifferent to whether the story is true.", "Fel. Hela texten är en granskning av om berättelsen stämmer; författaren bryr sig tydligt."),
        ],
        correct: 0,
        paragraph: 3,
      },
    ],
  },
  {
    id: "elf-val",
    title: "The Price of Too Many Choices",
    topic: "psykologi",
    paragraphs: [
      "In a famous experiment from the year 2000, two psychologists set up a tasting stall in an upmarket grocery store. On some days shoppers could sample twenty-four varieties of jam; on others, only six. The larger display drew more visitors, but far fewer of them bought anything: roughly three per cent of those who saw the big selection made a purchase, compared with nearly a third of those who saw the small one. The study became a staple of popular psychology, cited as proof that abundance paralyses us.",
      "Later attempts to repeat the experiment have been less tidy. A large review that pooled results from dozens of studies found that the effect of extra choice was, on average, close to zero. Yet the average concealed real variation: in some settings, more options clearly overwhelmed people, while in others they were welcomed. Choice seemed to become a burden mainly when the options were hard to compare, when the chooser lacked clear preferences, or when the decision carried a high risk of regret.",
      "These conditions suggest a more modest conclusion than the original headlines. People do not recoil from variety as such; they struggle when they have no way of sorting it. A shopper who knows exactly which coffee she likes will glide past a hundred rivals, whereas a newcomer to wine may freeze before a wall of unfamiliar labels, unsure what any of the differences mean.",
      "The practical advice for those designing menus, websites or pension plans is therefore not to cut choice indiscriminately, but to help people narrow it, through sensible defaults, clear categories and honest guidance. Abundance is not the enemy; disorder is. A well-organised shelf of fifty products can feel easier to navigate than a muddled one of ten, and the same is true of the screens we scroll through every day.",
    ],
    questions: [
      {
        id: "elf-val-1",
        type: "huvudtanke",
        prompt: "What is the main idea of the text?",
        options: [
          o("The original jam study was shown to be fraudulent.", "Står inte i texten. Studien kallas 'less tidy' att upprepa, men ingen anklagas för fusk. Påhittat."),
          o("Offering more options always makes people less likely to buy.", "Det är just den förenklade slutsatsen texten tillbakavisar. 'Always' är för starkt; stycke 2 visar att effekten varierar."),
          o("Whether extra choice overwhelms people depends on the circumstances, not on a general rule.", "Rätt. Stycke 2-3: effekten är nära noll i snitt men beror på om alternativen är jämförbara, om man har preferenser och om risken för ånger är hög."),
          o("Pension plans should offer only a few options.", "Sant men ur vinkel och för starkt. Stycke 4 säger att man inte ska skära ned valfriheten urskillningslöst, utan hjälpa folk att smalna av."),
        ],
        correct: 2,
        paragraph: 1,
      },
      {
        id: "elf-val-2",
        type: "detalj",
        prompt: "According to the review mentioned in the text, the average effect of extra choice was",
        options: [
          o("strongly negative in nearly all studies.", "Det är den ursprungliga studiens budskap, inte översiktens. Stycke 2: effekten var 'close to zero' i genomsnitt."),
          o("close to zero on average, but varying between settings.", "Rätt. Stycke 2: 'close to zero' men 'the average concealed real variation'."),
          o("strongly positive, as people welcomed variety.", "För starkt och fel. Vissa miljöer gav positiv effekt, men medelvärdet var nära noll, inte starkt positivt."),
          o("impossible to calculate because the studies differed.", "Fel. Översikten kom fram till ett medelvärde; olikheterna gjorde det bara missvisande."),
        ],
        correct: 1,
        paragraph: 1,
      },
      {
        id: "elf-val-3",
        type: "ordbetydelse",
        prompt: "In paragraph 3, the phrase 'glide past a hundred rivals' most nearly means",
        options: [
          o("admire a hundred competing products from a distance.", "Fel betydelse. 'Glide past' handlar om att passera obehindrat, inte om att beundra."),
          o("hurry through a shop in a bad temper.", "Fel ton. Bilden är lugn och smidig ('glide'); kunden vet vad hon vill ha."),
          o("reluctantly choose among many similar goods.", "Motsatsen. Hon väljer inte alls bland dem; hon vet redan vilket kaffe hon vill ha."),
          o("ignore many alternatives without difficulty.", "Rätt. Hon 'knows exactly which coffee she likes', så de hundra konkurrenterna stör henne inte."),
        ],
        correct: 3,
        paragraph: 2,
      },
    ],
  },
  {
    id: "elf-fyr",
    title: "Lights Out for the Lighthouse Keeper",
    topic: "teknik",
    paragraphs: [
      "For two centuries, a lighthouse was a household as much as a machine. A keeper, often with a wife and children, lived beside the lamp, trimmed its wick, polished its lenses and kept a daily log of weather and passing ships. The work was lonely and sometimes dangerous, yet it carried prestige, since sailors literally staked their lives on the keeper's diligence. A lamp that failed on a stormy night could mean a wreck by morning, and the keeper knew it.",
      "Automation ended this way of life with surprising speed. From the middle of the twentieth century, electric lamps, timers and light-sensitive switches made it possible to run a beacon without anyone present. Governments, concerned about cost, welcomed the change: a keeper's salary was a recurring expense, whereas a sensor was a one-off purchase. By the 1990s, the last staffed lights in many countries had been switched over, and the keepers' cottages were left to the weather or sold as holiday homes, often to people who had never seen the sea at its worst.",
      "Not everyone regards this as pure progress. Critics point out that the keeper was never merely a lamp-lighter; he also watched for vessels in distress and reported oddities that no instrument was built to notice. Others note that the machines themselves are fragile, depending on power supplies and satellite links that can fail together. Still, few mariners would willingly return to the old system, and the lights now shine more reliably than they ever did when tended by hand.",
    ],
    questions: [
      {
        id: "elf-fyr-1",
        type: "huvudtanke",
        prompt: "Which of the following best describes the text as a whole?",
        options: [
          o("It explains how automation replaced lighthouse keepers, bringing real gains but also some losses.", "Rätt. Stycke 1 beskriver yrket, 2 automatiseringen och kostnadsvinsten, 3 både kritik och slutsatsen att ljusen nu lyser tillförlitligare."),
          o("It argues that keepers were badly paid and glad to leave their posts.", "Står inte i texten. Lön nämns bara som en kostnad för staten, och keepers önskemål nämns aldrig."),
          o("It claims that automated lighthouses are less reliable than staffed ones.", "Motsatsen. Sista meningen: ljusen lyser nu 'more reliably' än när de sköttes för hand."),
          o("It urges governments to employ keepers again.", "För starkt och inte i texten. Även kritikerna nämns utan att kräva återgång; 'few mariners would willingly return'."),
        ],
        correct: 0,
        paragraph: 1,
      },
      {
        id: "elf-fyr-2",
        type: "detalj",
        prompt: "Why did governments welcome automation, according to the text?",
        options: [
          o("Keepers had asked to leave their lonely posts.", "Står inte i texten. Arbetet beskrivs som ensamt, men inga önskemål från vaktarna nämns."),
          o("Electric lamps were brighter than oil lamps.", "Kan vara sant, men det sägs inte. Statens skäl i stycke 2 var kostnaden."),
          o("A sensor was cheaper than a keeper's salary.", "Rätt. Stycke 2: 'a keeper's salary was a recurring expense, whereas a sensor was a one-off purchase'."),
          o("Sailors had complained about the keepers' diligence.", "Motsatsen. Sjömän litade på vaktarnas noggrannhet ('staked their lives on' den, stycke 1)."),
        ],
        correct: 2,
        paragraph: 1,
      },
      {
        id: "elf-fyr-3",
        type: "slutsats",
        prompt: "What can be inferred from the last paragraph?",
        options: [
          o("The author believes critics are entirely mistaken.", "För starkt. Författaren kallar det inte 'pure progress' och redovisar kritikernas poänger som verkliga."),
          o("The author sees the loss of the keepers' wider observations as a real drawback, though one that is outweighed.", "Rätt. Kritiken om vaktarnas övervakning redovisas seriöst, men 'few mariners would willingly return' och ljusen är mer pålitliga."),
          o("The author thinks satellite failures have caused many wrecks.", "Står inte i texten. Satellitlänkar nämns bara som en sårbarhet, inga olyckor."),
          o("The author wants keepers to replace the machines.", "Motsatsen. Slutet pekar på att återgång inte vore önskvärd för sjöfarare."),
        ],
        correct: 1,
        paragraph: 2,
      },
    ],
  },
  {
    id: "elf-skog",
    title: "Listening to the Forest",
    topic: "naturvetenskap",
    paragraphs: [
      "Counting wild animals is harder than it sounds. Birds hide in foliage, mammals move at night, and many amphibians are heard far more often than they are seen. Traditionally, ecologists have relied on trained observers who walk set routes at dawn, noting every species they identify. The method works, but it is slow, expensive and limited by the number of experts available. It also introduces a subtle bias, since two observers will rarely detect exactly the same birds, and a single person cannot be in a hundred places at once. Remote areas, where the most interesting species often live, are therefore the least well surveyed.",
      "Over the past decade, cheap digital recorders have begun to change this. A small waterproof unit, strapped to a tree and powered by a handful of batteries, can capture sound continuously for weeks. Researchers collect the memory cards, upload the recordings and let software search them for the calls of particular species. Because the recorder never tires and leaves almost no footprint, it can produce a record of an entire dawn chorus, night after night, from dozens of sites at once. The scale of data is simply beyond what human surveyors could gather.",
      "The difficulty has therefore moved from collection to interpretation. A single recorder may produce hundreds of hours of audio, most of it wind, rain and insects. Machine-learning programs trained on libraries of labelled calls now sift this material, flagging the sounds worth a human's attention. They are far from infallible: a model trained on birds from one continent can confuse the calls of unfamiliar species, and heavy rain can mask quieter singers entirely. Most teams therefore treat the software as an assistant that proposes candidates, with experts confirming the results.",
      "Even so, the results have been striking. In one project in tropical forest, researchers found that areas which looked healthy from the air were strangely silent, missing the larger birds and mammals that hunting had removed. Satellite images had recorded an intact canopy; the soundscape revealed an emptied one. Such discoveries matter because conservation money is often allocated on the basis of what can be seen from above, and an apparently green landscape may be hiding a quiet crisis.",
      "None of this makes the field observer obsolete. Sounds say little about an animal's age, health or breeding success, and silent species, such as many reptiles, escape the net altogether. The likeliest future is a partnership in which microphones supply breadth and people supply depth, each correcting the other's blind spots. That combination, cheap and tireless on one side, careful and discerning on the other, may prove more valuable than either approach alone, and it will almost certainly be cheaper than the alternative of doing nothing.",
    ],
    questions: [
      {
        id: "elf-skog-1",
        type: "huvudtanke",
        prompt: "What is the main point of the text?",
        options: [
          o("Machine-learning programs have made human ecologists unnecessary.", "Motsatsen och för starkt. Stycke 3 och 5: experter bekräftar resultaten och fältobservatören är inte föråldrad."),
          o("Satellite images are useless for tracking forest health.", "För starkt. Stycke 4 säger att bilderna missade tystnaden, inte att de är värdelösa."),
          o("Traditional bird surveys are inaccurate and should be abandoned.", "För starkt. Metoden kallas långsam och dyr, men 'The method works' (stycke 1), och människor behövs även framöver."),
          o("Sound recorders, software and human expertise together are changing how wildlife is monitored.", "Rätt. Texten följer kedjan: begränsningar med observatörer, inspelare, mjukvara, fynd och partnerskapet i slutet."),
        ],
        correct: 3,
        paragraph: 1,
      },
      {
        id: "elf-skog-2",
        type: "detalj",
        prompt: "What did the tropical forest project reveal?",
        options: [
          o("Forests that looked intact from above had lost many of their larger animals.", "Rätt. Stycke 4: områden som såg friska ut från luften saknade 'the larger birds and mammals'."),
          o("Satellite images had overestimated the amount of canopy.", "Motsatsen. Bilderna 'had recorded an intact canopy'; trädtaket fanns, det var djuren som saknades."),
          o("Hunting had greatly increased the number of small birds.", "Står inte i texten. Jakt nämns bara som orsak till att större djur försvunnit."),
          o("Heavy rain made quieter species impossible to detect.", "Sant men irrelevant. Regnet är en svaghet som nämns i stycke 3, inte vad skogsprojektet visade."),
        ],
        correct: 0,
        paragraph: 3,
      },
      {
        id: "elf-skog-3",
        type: "ordbetydelse",
        prompt: "In the final paragraph, the phrase 'escape the net altogether' most nearly means",
        options: [
          o("become protected by law.", "Fel betydelse. Bilden gäller upptäckt, inte lagskydd."),
          o("be recorded more often than other species.", "Motsatsen. Tysta arter som många reptiler fångas inte upp alls."),
          o("remain completely undetected by the method.", "Rätt. 'Silent species' ger inga ljud som mikrofonerna kan fånga, så de slinker helt förbi."),
          o("move away from the researchers' equipment.", "Fel. Texten talar om att arterna är tysta, inte att de flyttar sig."),
        ],
        correct: 2,
        paragraph: 4,
      },
    ],
  },
  {
    id: "elf-jarnvagstid",
    title: "Keeping Railway Time",
    topic: "historia",
    paragraphs: [
      "Until the nineteenth century, noon was a local affair. Every town set its clocks by the sun, so that when it was twelve in one place it was a few minutes earlier or later in another a short distance east or west. For people who travelled on foot or by coach, the difference mattered little: a journey took so long that a discrepancy of a quarter of an hour was lost in the general uncertainty of the road. Time was something a community shared, not something a nation imposed, and nobody felt the lack of a standard.",
      "The railways changed that. A train travelling at forty miles an hour crossed several local times in an afternoon, and a timetable that tried to list each town's own noon would have been unreadable. More alarmingly, trains sharing a single track needed to agree exactly when each would be where, since a mistake of minutes could end in a collision. In Britain, the companies began in the 1840s to run their services by the time kept at London, which became known as railway time. The arrangement saved confusion, and it saved a good deal of money for companies tired of printing conflicting tables.",
      "Not everyone welcomed this. Some towns clung to their own clocks, and a few public buildings displayed two hands, one for local time and one for the railway's. Objectors argued that to adopt London's time was to surrender a local freedom to distant businessmen. Yet the practical advantages were hard to resist. Within a few years most public clocks followed the railway, and in 1880 Parliament made it the law, recognising what had already become the habit of the country.",
      "Similar pressures arose elsewhere, and on a larger scale. In North America, with its continental distances, railway companies at one stage used dozens of separate times. In 1883 they agreed to divide the continent into zones, each an hour apart, a scheme adopted internationally the following year. The new arrangement was a compromise: it gave up the sun's precision in return for coordination, and it accepted that noon would often fall when the sun was not directly overhead. Few travellers at the time seem to have minded the sacrifice for long.",
      "It is easy to see this story as one of simple progress, but it also marks a quiet shift in how people experienced time. When the clock on the station wall began to command the day, punctuality turned from a courtesy into a duty. The habit of living by shared, exact minutes, so natural to us, is therefore younger than many suppose, and it was born less of philosophy than of the practical need to keep trains from colliding.",
    ],
    questions: [
      {
        id: "elf-jarnvagstid-1",
        type: "huvudtanke",
        prompt: "Which statement best sums up the text?",
        options: [
          o("Parliament abolished local time because it was inaccurate.", "Fel. Stycke 3: lagen 1880 erkände bara vad som redan blivit sedvana, och orsaken var järnvägarnas behov, inte noggrannhet."),
          o("The railways created a need for shared time, which gradually replaced local time and changed habits.", "Rätt. Stycke 1-2 visar behovet, 3-4 införandet och 5 vanorna som förändrades."),
          o("Public buildings were the main opponents of railway time.", "Bara en del och en överdrift. Stycke 3 nämner att några byggnader visade två tider, men det är en detalj."),
          o("Time zones were invented in Britain and later copied in North America.", "Inte i texten. Zonerna i Nordamerika (stycke 4) var en separat lösning på kontinentala avstånd; Storbritannien införde en enda tid."),
        ],
        correct: 1,
        paragraph: 1,
      },
      {
        id: "elf-jarnvagstid-2",
        type: "detalj",
        prompt: "Why did local differences in time matter little to travellers before the railways?",
        options: [
          o("They had no clocks to compare.", "Står inte i texten. Orsaken var resornas långsamhet, inte avsaknaden av klockor."),
          o("All towns used the same time.", "Motsatsen. Stycke 1: varje stad ställde klockorna efter solen och tiderna skilde sig."),
          o("Coach drivers kept time by London.", "Står inte i texten. London som referens kom först med järnvägarna (stycke 2)."),
          o("Journeys were so slow that small differences were lost in general uncertainty.", "Rätt. Stycke 1: 'a journey took so long that a discrepancy of a quarter of an hour was lost in the general uncertainty'."),
        ],
        correct: 3,
        paragraph: 0,
      },
      {
        id: "elf-jarnvagstid-3",
        type: "syfte",
        prompt: "What is the author's main purpose in the final paragraph?",
        options: [
          o("To suggest that the modern habit of exact shared time has a recent, practical origin.", "Rätt. 'Younger than many suppose' och 'born less of philosophy than of the practical need to keep trains from colliding'."),
          o("To criticise the railway companies for forcing punctuality on people.", "Författaren kritiserar inte; tonen är reflekterande. 'Duty' beskrivs som ett skifte, inte ett övergrepp."),
          o("To argue that people were happier before the arrival of clocks.", "Står inte i texten. Inget sägs om lycka."),
          o("To prove that time zones are unnatural.", "För starkt. Texten kallar dem ett 'compromise', inte onaturliga eller bevisat fel."),
        ],
        correct: 0,
        paragraph: 4,
      },
    ],
  },
  {
    id: "elf-oversattning",
    title: "The Invisible Art of Translation",
    topic: "kultur",
    paragraphs: [
      "Readers of translated novels rarely think about who stands between them and the author. The name on the cover belongs to the writer; the translator's, if it appears at all, is printed in small type on the title page. Yet every sentence a reader meets in such a book was chosen by someone else. A translator makes thousands of decisions about word order, tone and idiom, and no two translators would produce the same English version of the same page. The reader who believes that a book simply arrives in English, untouched, has been quietly misled by the convention of the cover.",
      "The trade has long prized a certain kind of modesty. A good translation, according to a widely held view, is one that does not read like a translation: smooth, natural, and free of the awkwardness that betrays a foreign origin. This ideal has an obvious appeal, as nobody enjoys stumbling over clumsy phrases. But it also has a cost. By aiming for invisibility, translators may erase precisely the strangeness that makes foreign writing worth reading, turning a distinctive voice into something comfortably familiar. A reader may finish the book without ever learning how unusual its author really sounded.",
      "Consider a writer whose sentences run on for a page, held together by commas and subordinate clauses. In a language that prefers short sentences, a translator faces a choice. Breaking the sentence up produces something readable, but the dizzying momentum that defined the original is lost. Preserving the length keeps the effect, but risks a sentence that readers find exhausting. Neither option is wrong, and neither is neutral; each is an interpretation of what the author was trying to do. The difference may seem small on one page, but across three hundred it shapes the character of the whole book.",
      "Some publishers and critics have begun to argue for a different approach, in which translations are allowed to feel slightly foreign and the translator is credited prominently. Supporters say this respects both the reader and the original. Sceptics reply that most readers want a story, not a lesson in linguistics, and that a text which keeps drawing attention to itself is a failure of craft rather than an act of fidelity. Both arguments are made in good faith, and each can point to celebrated examples that appear to prove it.",
      "The debate is unlikely to be settled, partly because both sides are right about something. What it has achieved is to make a hidden profession a little more visible. Readers who now ask who translated a book, and why it reads as it does, have understood that a translation is not a window onto the original but a version of it, made by a person with a point of view.",
    ],
    questions: [
      {
        id: "elf-oversattning-1",
        type: "huvudtanke",
        prompt: "What is the main idea of the text?",
        options: [
          o("Most translations are too awkward to be enjoyable.", "Fel. Texten säger att ideal-översättningen är len och naturlig; klumpighet är något översättare försöker undvika."),
          o("Translators ought to be better paid and named on book covers.", "Bara en del. Synlig kreditering nämns i stycke 4, men lön nämns aldrig och det är inte textens kärna."),
          o("Translation involves interpretive choices, and the ideal of the invisible translator is open to debate.", "Rätt. Stycke 1 och 3 visar valen, stycke 2 och 4 diskuterar idealet med osynlighet."),
          o("Short sentences are better than long ones in English.", "Står inte i texten. Stycke 3 säger att varken korta eller långa val är fel."),
        ],
        correct: 2,
        paragraph: 1,
      },
      {
        id: "elf-oversattning-2",
        type: "detalj",
        prompt: "According to paragraph 3, what is the drawback of breaking up a very long sentence?",
        options: [
          o("The sense of momentum that characterised the original is lost.", "Rätt. Stycke 3: 'the dizzying momentum that defined the original is lost'."),
          o("The result becomes harder to read.", "Motsatsen. Att dela upp ger 'something readable'; det är den långa meningen som riskerar att tröttas ut på."),
          o("Every word in the sentence changes meaning.", "För starkt. Texten talar om effekt och tempo, inte om att alla ord får ny betydelse."),
          o("It is considered wrong by the profession.", "Motsatsen. 'Neither option is wrong.'"),
        ],
        correct: 0,
        paragraph: 2,
      },
      {
        id: "elf-oversattning-3",
        type: "syfte",
        prompt: "How does the author regard the dispute between the two approaches?",
        options: [
          o("As already settled in favour of foreign-sounding translations.", "Motsatsen. Stycke 5: 'unlikely to be settled'."),
          o("As pointless, since readers do not care about translators.", "Fel. Stycke 5 säger att debatten har gjort yrket mer synligt och att läsare nu frågar efter översättaren."),
          o("As harmful to the translating profession.", "Står inte i texten. Debatten beskrivs snarare som nyttig genom att göra yrket synligt."),
          o("As unresolved, with each side making a valid point.", "Rätt. 'Both sides are right about something' (stycke 5)."),
        ],
        correct: 3,
        paragraph: 4,
      },
    ],
  },
  {
    id: "elf-jord",
    title: "The Slow Science of Soil",
    topic: "naturvetenskap",
    paragraphs: [
      "To most of us, soil is simply what plants grow in, and it receives about as much attention as the floor beneath our feet. Scientists who study it take a rather different view. A teaspoon of healthy garden soil can contain more living organisms than there are people on Earth, most of them bacteria and fungi too small to see. These communities break down dead material, release nutrients, bind particles into crumbs and hold water against drought. Without them, the plants that feed us would struggle, and yet we understand them far less well than we understand the stars.",
      "One reason for this neglect is practical. Soil is opaque, so researchers cannot watch it at work as they might watch a coral reef. Digging samples out disturbs the delicate structures they hope to examine, and when microbes are brought into a laboratory most refuse to grow. For much of the twentieth century this meant that scientists could study only the small fraction of soil species that tolerated life in a dish, and they mistook that fraction for the whole community. The picture changed only when techniques for reading genetic material directly from soil made it possible to identify organisms without cultivating them.",
      "The results were humbling. Even in a single field, thousands of species turned out to be new to science, and the relationships among them proved far more intricate than anyone had imagined. Fungal threads, for instance, connect the roots of different plants, trading sugars from one for minerals from another. Some researchers have described these networks as a kind of underground marketplace, though the metaphor is contested: critics warn that it attributes to fungi a generosity or strategy they may not possess, and that evidence for the sharing of resources between neighbouring trees remains thinner than popular accounts suggest.",
      "The practical consequences are considerable. Intensive farming, with its repeated ploughing and heavy use of chemical inputs, tends to reduce the diversity of soil life, and some studies link this loss to declining fertility. Farmers who plant cover crops, reduce tilling or add organic matter often report improvements, but the evidence is uneven. Results depend heavily on climate, soil type and the time scale considered, and a technique that revives one field may do little for another a few miles away. Anyone offering a single recipe for healthy soil should be treated with caution.",
      "Slow is, in any case, the operative word. Soil forms at a pace measured in centuries, and recovering its richness after damage can take longer than a farmer's career. Experiments designed to track change therefore demand patience that sits awkwardly with the funding cycles of modern research, which usually reward results within a few years. Some of the most valuable data come from plots that were set up over a century ago, by scientists who could not have known what questions their successors would ask. Without their patience, a great deal of what is now known would simply be missing, and it could not be recreated today at any price.",
      "Time is also what makes the field hard to explain to the public. A drought, a flood or a failed harvest produces an image and a headline; a gradual decline in microbial diversity produces neither. The danger is that damage which is invisible and slow will be judged unimportant simply because nobody can photograph it, and that attention will arrive only once the consequences are too large to ignore.",
      "What emerges is a field in which humility is the appropriate attitude. We have learned just enough to realise how much remains unknown, and enough to suspect that the cost of ignoring the unseen is real. Soil may never inspire the awe that galaxies do, but anyone who eats has a stake in its future, and a more curious attitude to it would be a modest investment against an uncertain harvest. If the past century taught us how much a little knowledge can change a farm, the next may teach us how much more we still have to learn.",
    ],
    questions: [
      {
        id: "elf-jord-1",
        type: "huvudtanke",
        prompt: "Which statement best expresses the main idea of the text?",
        options: [
          o("Soil is a complex and poorly understood living system, and claims about managing it call for caution.", "Rätt. Stycke 1-3 visar komplexiteten och okunnigheten, 4 och 7 manar till försiktighet och ödmjukhet."),
          o("Intensive farming has permanently destroyed soil life in most regions.", "För starkt. Stycke 4 säger att odling 'tends to reduce' mångfalden och att bevisen är ojämna; 'permanently' och 'most regions' står inte där."),
          o("Fungal networks are proven to share resources between trees, as popular accounts claim.", "Motsatsen. Stycke 3: bevisen är 'thinner than popular accounts suggest'."),
          o("New laboratory techniques have solved the mystery of soil life.", "Motsatsen. Genetiska metoder avslöjade mycket nytt men stycke 7: 'how much remains unknown'."),
        ],
        correct: 0,
        paragraph: 6,
      },
      {
        id: "elf-jord-2",
        type: "detalj",
        prompt: "Why did scientists for decades study only a small part of soil life?",
        options: [
          o("Most soil organisms are extremely rare.", "Fel. Stycke 1 säger att det finns enormt många organismer i jord."),
          o("Researchers were uninterested in microbes.", "Motsatsen. De ville undersöka dem ('hope to examine', stycke 2), men metoderna räckte inte."),
          o("Most microbes would not grow in the laboratory.", "Rätt. Stycke 2: 'when microbes are brought into a laboratory most refuse to grow'."),
          o("Genetic techniques were not permitted.", "Fel. Genetiska metoder fanns inte ännu; ingen förbjöd dem."),
        ],
        correct: 2,
        paragraph: 1,
      },
      {
        id: "elf-jord-3",
        type: "syfte",
        prompt: "Why does the author mention the 'underground marketplace' image?",
        options: [
          o("To prove that fungi trade in a strategic way.", "Motsatsen. Författaren säger att metaforan är omstridd och kanske tillskriver svampar förmågor de inte har."),
          o("To illustrate a popular picture while noting that it may overstate the evidence.", "Rätt. Stycke 3: 'though the metaphor is contested' och bevisen är tunnare än populära framställningar."),
          o("To criticise researchers who study fungi.", "Fel. Forskarna beskrivs som ödmjuka; ingen kritik riktas mot studiet av svampar."),
          o("To show that trees trade directly with farmers.", "Påhittat. Handeln gäller växter och svampar under jord, inte bönder."),
        ],
        correct: 1,
        paragraph: 2,
      },
      {
        id: "elf-jord-4",
        type: "slutsats",
        prompt: "What can be concluded from paragraph 4 about advice on healthy soil?",
        options: [
          o("Cover crops are ineffective.", "För starkt. Bönder 'often report improvements'; bevisen är ojämna, inte negativa."),
          o("Farmers should stop ploughing immediately.", "Står inte i texten. Ingen sådan uppmaning ges."),
          o("Chemical inputs reliably increase soil diversity.", "Motsatsen. Kemiska insatser nämns som något som tenderar att minska mångfalden."),
          o("A method that works in one place may not work in another.", "Rätt. 'A technique that revives one field may do little for another a few miles away.'"),
        ],
        correct: 3,
        paragraph: 3,
      },
    ],
  },
  {
    id: "elf-triage",
    title: "The Algorithm in the Waiting Room",
    topic: "teknik",
    paragraphs: [
      "A casualty department at night is a place of constant triage. Nurses glance at a patient, ask a few questions, check a pulse and decide, within minutes, who must be seen at once and who can safely wait. The skill involved is hard to describe and harder to teach, as it rests on years of exposure to the many ways in which illness presents itself. Errors are inevitable, and the consequences can be grave: a patient whose chest pain is mistaken for indigestion may deteriorate in a corridor while others are treated ahead of them, even though nobody in the room intended it, and the error may only become visible hours later.",
      "It is against this background that hospitals have begun to experiment with software that estimates how urgent a patient's condition is. Such programs are trained on large collections of past records, learning which combinations of symptoms, vital signs and medical history tended to precede serious outcomes. When a new patient arrives, the program offers a score, which the staff may accept, adjust or ignore. Proponents argue that a tool that never tires and never has a bad night can catch patterns that an exhausted human overlooks. In a department where a single nurse may be watching a dozen patients, that second pair of eyes could prove decisive.",
      "Early results are encouraging but mixed. In some trials, the software identified patients at risk of sudden deterioration hours before staff did. In others, it generated so many false alarms that nurses learned to dismiss its warnings, a phenomenon familiar from car alarms and, in medicine, known as alert fatigue. A tool that is right most of the time can still do harm if it is wrong in ways that are hard to anticipate, or if it persuades busy people to trust it more than they should. Evidence from other professions suggests that people grow complacent when a machine is usually right, and the rare failure then goes unnoticed.",
      "A subtler problem lies in the data. A program learns from what has happened, and what has happened reflects past practice, with all its blind spots. If, historically, women's heart attacks were recognised later than men's, or if patients who spoke little English were taken less seriously, a system trained on those records may quietly reproduce the pattern, and it will do so with the authority of a number. Auditing for such bias is possible, but only if developers know to look and if hospitals are willing to publish what they find. Commercial secrecy about how a product works can make independent checking harder than it ought to be.",
      "There is also the question of who is responsible when things go wrong. If a nurse follows the software's advice and a patient is harmed, is the fault hers, the manufacturer's or the hospital's? If she overrides it and is proved right, will her judgement be rewarded, or will she be asked to justify why she disregarded the evidence? How such questions are answered will shape whether clinicians feel the software is a colleague or a surveillance device, and that in turn will affect whether they use it well. Trust, once lost in the first months of a rollout, is notoriously hard to win back.",
      "None of this amounts to an argument against the technology. Triage is already imperfect, and a carefully tested aid could save lives. But the lesson of the early trials is that a tool's accuracy in the laboratory is only the beginning. What matters is how it behaves in a crowded ward at four in the morning, in the hands of people who are tired, interrupted and responsible for a dozen things at once. Hospitals that treat deployment as a question of design and training, not merely of purchase, are likely to fare best. They will also, one suspects, be the ones that listen carefully to the nurses who use the system every night and who notice its faults first.",
    ],
    questions: [
      {
        id: "elf-triage-1",
        type: "huvudtanke",
        prompt: "What is the main message of the text?",
        options: [
          o("Triage software will soon replace nurses in casualty departments.", "Fel. Programmet ger bara en poäng som personalen kan godta, justera eller ignorera (stycke 2); ersättning nämns aldrig."),
          o("Alert fatigue makes all medical software useless.", "För starkt. Alert fatigue är ett problem i vissa försök (stycke 3), men andra försök visade tidig upptäckt."),
          o("Hospitals should wait to use any technology until bias has been eliminated.", "Står inte i texten. Stycke 6 säger tvärtom att texten inte är ett argument mot tekniken."),
          o("Triage software may help, but the benefit depends on how it is tested, introduced and used.", "Rätt. Stycke 3-5 tar upp risker och stycke 6 sammanfattar: laboratorienoggrannhet är 'only the beginning'; design och utbildning avgör."),
        ],
        correct: 3,
        paragraph: 5,
      },
      {
        id: "elf-triage-2",
        type: "detalj",
        prompt: "What is meant by 'alert fatigue' in paragraph 3?",
        options: [
          o("Nurses become physically exhausted by long night shifts.", "Sant men irrelevant. Utmattning från nattskift nämns i stycke 2 som ett argument för programmet, men 'alert fatigue' betyder något annat."),
          o("Staff begin to ignore warnings because too many of them are false.", "Rätt. Stycke 3: 'so many false alarms that nurses learned to dismiss its warnings', som bilarmen."),
          o("The software stops producing alerts when it is overloaded.", "Står inte i texten. Problemet ligger hos människorna som slutar lyssna, inte hos programmet."),
          o("Patients grow tired of waiting for alerts to sound.", "Fel. Begreppet gäller personalens reaktion på varningar, inte patienternas väntan."),
        ],
        correct: 1,
        paragraph: 2,
      },
      {
        id: "elf-triage-3",
        type: "slutsats",
        prompt: "What does the author suggest about software trained on historical records?",
        options: [
          o("It may repeat past unfairness while appearing objective.", "Rätt. Stycke 4: den kan 'quietly reproduce the pattern' 'with the authority of a number'."),
          o("It is always more biased than human nurses.", "För starkt. Texten jämför inte generellt, och 'always' går inte att belägga."),
          o("It cannot be checked for bias.", "Motsatsen. 'Auditing for such bias is possible' (stycke 4), om utvecklarna vet att leta."),
          o("It will treat women and men identically.", "Motsatsen. Exemplet visar hur historiska skillnader kan föras vidare."),
        ],
        correct: 0,
        paragraph: 3,
      },
      {
        id: "elf-triage-4",
        type: "ordbetydelse",
        prompt: "In paragraph 5, the phrase 'a surveillance device' suggests that clinicians might see the software as",
        options: [
          o("a tool that improves their pay.", "Fel. Inget i stycket handlar om lön; kontrastbegreppet är 'a colleague'."),
          o("a record of patients' symptoms.", "Fel betydelse. 'Surveillance' handlar om övervakning av personalen, inte om journalföring."),
          o("something used to monitor and judge them.", "Rätt. Stycket frågar om sjuksköterskan måste 'justify' att hon ignorerat programmet, alltså kontroll i stället för kollegialt stöd."),
          o("a way of protecting patients from harm.", "Fel poäng. Kontrasten till 'colleague' gäller hur personalen upplever det, inte patientskydd."),
        ],
        correct: 2,
        paragraph: 4,
      },
    ],
  },
  {
    id: "elf-lucka-reparation",
    title: "Gap-fill: The Quiet Economics of Repair",
    topic: "samhälle",
    paragraphs: [
      "For most of the twentieth century, repairing a broken toaster or a worn pair of shoes was an ordinary (1) ___ of household life. Today, many people simply throw such items away and buy new ones, partly because modern products are often built (2) ___ they cannot easily be opened. Glued casings, sealed batteries and unusual screws make even a simple repair a task for specialists, and often a more expensive one than a replacement.",
      "The cost of this habit is considerable. Electronic waste is the fastest-growing category of household refuse, and much of it ends up in landfills, (3) ___ valuable metals that could have been recovered. Campaigners therefore argue for a legal right to repair, which would oblige manufacturers to sell spare parts and publish manuals. Manufacturers reply that independent repairers may (4) ___ safety standards, and that sealed designs make devices thinner, lighter and more resistant to water.",
      "Whatever the merits of either side, there are signs that opinion is shifting. Repair cafés, where volunteers help neighbours mend appliances for free, have spread across Europe, and several governments have cut taxes (5) ___ repair work. The question is no longer whether people want to mend things, but whether the products they buy will let them. For many shoppers, that may soon become a deciding factor.",
    ],
    questions: [
      {
        id: "elf-lucka-reparation-1",
        type: "ordbetydelse",
        prompt: "Which alternative best fits gap (1)?",
        options: [
          o("ambition", "Fel ord. 'An ambition of household life' ger ingen mening; reparation var något vanligt, inte ett mål."),
          o("penalty", "Fel. Ett 'penalty' är ett straff; meningen beskriver något helt vardagligt."),
          o("tribute", "Fel kollokation. 'Tribute' betyder hyllning och passar inte med 'ordinary' och vardagsliv."),
          o("feature", "Rätt. 'An ordinary feature of household life' = en vanlig del av hushållets vardag."),
        ],
        correct: 3,
        paragraph: 0,
      },
      {
        id: "elf-lucka-reparation-2",
        type: "ordbetydelse",
        prompt: "Which alternative best fits gap (2)?",
        options: [
          o("so that", "Rätt. 'Built so that they cannot easily be opened' uttrycker avsikt/resultat; efterföljande 'Glued casings...' bekräftar det."),
          o("in spite of", "Fel samband. 'In spite of' kräver ett substantiv eller -ing-form och ger motsägelse: produkterna byggs inte trots att de inte kan öppnas."),
          o("unless", "Fel logik. 'Unless' betyder 'om inte' och ger ingen mening här."),
          o("as though", "Fel. 'As though' (som om) kräver ett jämförande sammanhang, inte en avsikt."),
        ],
        correct: 0,
        paragraph: 0,
      },
      {
        id: "elf-lucka-reparation-3",
        type: "ordbetydelse",
        prompt: "Which alternative best fits gap (3)?",
        options: [
          o("waste", "Fel form. Efter 'landfills,' behövs en particip som beskriver resultatet; 'waste' ger inget korrekt satsled."),
          o("to waste", "Fel. 'To waste' skulle uttrycka syfte, men skräpet hamnar inte där för att slösa metall."),
          o("wasted", "Fel form. 'Wasted' vore passiv och passar inte med objektet 'valuable metals'."),
          o("wasting", "Rätt. Presensparticip 'wasting valuable metals' är en aktiv bisats som beskriver följden."),
        ],
        correct: 3,
        paragraph: 1,
      },
      {
        id: "elf-lucka-reparation-4",
        type: "ordbetydelse",
        prompt: "Which alternative best fits gap (4)?",
        options: [
          o("underline", "Fel betydelse. 'Underline' = understryka; det passar inte som tillverkarnas invändning."),
          o("undermine", "Rätt. 'Undermine safety standards' = underminera säkerhetsnormer; det är tillverkarnas argument mot reparatörer."),
          o("undertake", "Fel kollokation. 'Undertake' = åta sig; man åtar sig en uppgift, inte standarder."),
          o("undergo", "Fel. 'Undergo' = genomgå; standarder genomgår inte något som reparatörer gör."),
        ],
        correct: 1,
        paragraph: 1,
      },
      {
        id: "elf-lucka-reparation-5",
        type: "ordbetydelse",
        prompt: "Which alternative best fits gap (5)?",
        options: [
          o("by", "Fel preposition. 'Cut taxes by' kräver en mängd (by 10 per cent), inte ett objekt."),
          o("at", "Fel. 'At repair work' ger ingen kollokation med skatter."),
          o("on", "Rätt. 'Taxes on repair work' är fast kollokation: skatter på något."),
          o("of", "Fel. 'Taxes of repair work' låter fel; 'of' anger inte vad som beskattas."),
        ],
        correct: 2,
        paragraph: 2,
      },
    ],
  },
  {
    id: "elf-lucka-drommar",
    title: "Gap-fill: Why Dreams Slip Away",
    topic: "psykologi",
    paragraphs: [
      "Most people can recall only a fragment of their dreams, and many remember none at all. The explanation is not that dreams fail to happen, but that the brain is poorly (1) ___ to store them. During the dreaming phase of sleep, the chemicals involved in forming lasting memories are present in unusually low amounts, so experiences are scarcely recorded in the first place. Memory, in short, depends on chemistry as much as on attention.",
      "Dreams that wake us abruptly are an exception, since the memory may remain accessible for a few minutes. Without such an interruption, the (2) ___ of dreams are lost within moments of waking, which is why nightmares are often remembered while peaceful dreams are not. Writing a dream down at once helps, (3) ___ even a short delay allows the details to fade. Many people who keep a dream diary report that their recall improves after only a few weeks of practice.",
      "Some researchers suggest that forgetting dreams may even be (4) ___ to the mind. If every strange scenario were stored alongside real experiences, we might find it hard to tell memory from fantasy, and the ordinary business of remembering what actually happened would become more uncertain. Forgetting, in other words, may be the price we pay for a clear sense of what is real and what is imagined.",
    ],
    questions: [
      {
        id: "elf-lucka-drommar-1",
        type: "ordbetydelse",
        prompt: "Which alternative best fits gap (1)?",
        options: [
          o("entitled", "Fel kollokation. 'Entitled to' betyder berättigad; hjärnan har inga rättigheter i det här sammanhanget."),
          o("persuaded", "Fel betydelse. 'Persuaded' = övertygad; passar inte med 'to store'."),
          o("acquainted", "Fel. 'Acquainted with' är den fasta konstruktionen och betyder bekant med."),
          o("equipped", "Rätt. 'Poorly equipped to store them' = dåligt rustad för att lagra dem; stämmer med låga minneskemikalier."),
        ],
        correct: 3,
        paragraph: 0,
      },
      {
        id: "elf-lucka-drommar-2",
        type: "ordbetydelse",
        prompt: "Which alternative best fits gap (2)?",
        options: [
          o("majority", "Rätt. 'The majority of dreams' är en fast kollokation (med 'the' före luckan)."),
          o("most", "Fel grammatik. 'The most of dreams' fungerar inte; 'most' står utan 'the'."),
          o("largest", "Fel. 'The largest of dreams' skulle jämföra enskilda drömmar, inte mängden."),
          o("much", "Fel. 'Much' används med oräkneliga substantiv och passar inte med 'the ... of dreams ... are'."),
        ],
        correct: 0,
        paragraph: 1,
      },
      {
        id: "elf-lucka-drommar-3",
        type: "ordbetydelse",
        prompt: "Which alternative best fits gap (3)?",
        options: [
          o("although", "Fel samband. 'Although' ger en motsättning, men meningen anger en orsak."),
          o("unless", "Fel. 'Unless' (om inte) vänder på logiken."),
          o("because", "Rätt. Att skriva direkt hjälper eftersom även en kort fördröjning gör att detaljer bleknar."),
          o("whereas", "Fel. 'Whereas' markerar kontrast, inte orsak."),
        ],
        correct: 2,
        paragraph: 1,
      },
      {
        id: "elf-lucka-drommar-4",
        type: "ordbetydelse",
        prompt: "Which alternative best fits gap (4)?",
        options: [
          o("detrimental", "Motsatsen. 'Detrimental' = skadlig, men nästa mening beskriver en fördel med att glömma."),
          o("beneficial", "Rätt. 'Beneficial to the mind' = nyttigt för medvetandet; förklaras av att vi annars blandar ihop minne och fantasi."),
          o("irrelevant", "Fel. Då skulle resonemanget om minnesförvirring sakna poäng."),
          o("reluctant", "Fel användning. 'Reluctant' (ovillig) beskriver personer, inte ett förhållande 'to the mind'."),
        ],
        correct: 1,
        paragraph: 2,
      },
    ],
  },
];

/** Provnivå-texterna först, så de delas ut före de äldre. */
export const HP_ELF_TEXTS: HpLasText[] = [...HP_ELF_TEXTS_HP, ...HP_ELF_TEXTS_BAS];
