// HP ORD-drill: målord från gamla högskoleprov (studera.nu/UHR).
// Svarsalternativ och förklaringar är egna — UHR:s uppgifter kopieras inte.

export interface HpWord {
  id: string;
  word: string;
  /** Fem svarsalternativ, som på provet. */
  options: [string, string, string, string, string];
  /** Index (0–4) för rätt alternativ i options. */
  correct: number;
  /** Kort egen förklaring eller exempelmening, visas efter svar. */
  explanation: string;
  /** Vilket prov ordet förekom på, t.ex. "HT2025". */
  source: string;
}

export const HP_WORDS: HpWord[] = [
  {
    id: "lägga-band-på-sig",
    word: "lägga band på sig",
    options: ["behärska sig", "ändra sig", "bestämma sig", "förbättra sig", "ge upp"],
    correct: 0,
    explanation: "Att lägga band på sig betyder att hålla tillbaka en impuls, t.ex. att inte säga vad man tänker.",
    source: "HT2025",
  },
  {
    id: "offert",
    word: "offert",
    options: ["faktura", "kostnadsförslag", "beställning", "orderbekräftelse", "affärsavtal"],
    correct: 1,
    explanation: "En offert är ett skriftligt förslag på pris för en vara eller tjänst, innan affären blir av.",
    source: "HT2025",
  },
  {
    id: "proportionerlig",
    word: "proportionerlig",
    options: ["relativt stor", "noga uträknad", "väl avpassad", "neutral", "felfri"],
    correct: 2,
    explanation: "Proportionerlig betyder att delarna eller storleken står i rätt förhållande till helheten.",
    source: "HT2025",
  },
  {
    id: "hektar",
    word: "hektar",
    options: ["viktenhet", "längdmått", "volymenhet", "ytmått", "avståndsmått"],
    correct: 3,
    explanation: "En hektar är ett mått på markyta, 10 000 kvadratmeter.",
    source: "HT2025",
  },
  {
    id: "sedermera",
    word: "sedermera",
    options: ["på en gång", "då och då", "för länge sedan", "när som helst", "så småningom"],
    correct: 4,
    explanation: "Sedermera används om något som hände senare i en följd av händelser.",
    source: "HT2025",
  },
  {
    id: "attribut",
    word: "attribut",
    options: ["kännetecken", "villkor", "innehåll", "begåvning", "utfyllnad"],
    correct: 0,
    explanation: "Ett attribut är en egenskap som är typisk eller kännetecknande för något.",
    source: "HT2025",
  },
  {
    id: "snarstucken",
    word: "snarstucken",
    options: ["svårfångad", "lättstött", "oansvarig", "oförsiktig", "snabbtänkt"],
    correct: 1,
    explanation: "Den som är snarstucken blir lätt sårad eller förnärmad.",
    source: "HT2025",
  },
  {
    id: "maskopi",
    word: "maskopi",
    options: ["oväntat bakslag", "pinsamt misslyckande", "hemligt samförstånd", "falsk identitet", "underjordisk rörelse"],
    correct: 2,
    explanation: "Maskopi betyder att flera samarbetar hemligt, ofta i något ohederligt syfte.",
    source: "HT2025",
  },
  {
    id: "perforera",
    word: "perforera",
    options: ["snygga till", "visa upp", "sätta fast", "göra hål i", "vika ihop"],
    correct: 3,
    explanation: "Att perforera något är att göra små hål i det, t.ex. frimärken.",
    source: "HT2025",
  },
  {
    id: "eterisk",
    word: "eterisk",
    options: ["giftig", "explosiv", "frätande", "trögflytande", "flyktig"],
    correct: 4,
    explanation: "Eterisk kan beskriva ämnen som lätt avdunstar, eller något som känns overkligt lätt.",
    source: "HT2025",
  },
  {
    id: "hereditär",
    word: "hereditär",
    options: ["ärftlig", "smittsam", "långvarig", "inbillad", "allvarlig"],
    correct: 0,
    explanation: "Hereditär betyder att något går i arv, t.ex. en sjukdom.",
    source: "HT2025",
  },
  {
    id: "underrätta",
    word: "underrätta",
    options: ["stötta", "informera", "tona ner", "läxa upp", "förolämpa"],
    correct: 1,
    explanation: "Att underrätta någon är att formellt meddela dem något.",
    source: "HT2025",
  },
  {
    id: "huskur",
    word: "huskur",
    options: ["fönsternisch", "helrenovering", "folklig behandlingsmetod", "spontan hyllning", "invigningsfest"],
    correct: 2,
    explanation: "En huskur är ett enkelt, ofta traditionellt sätt att bota krämpor hemma.",
    source: "HT2025",
  },
  {
    id: "trångsynt",
    word: "trångsynt",
    options: ["glömsk", "pessimistisk", "ouppmärksam", "fördomsfull", "kritisk"],
    correct: 3,
    explanation: "Trångsynt betyder att ha en snäv och oflexibel syn på saker.",
    source: "HT2025",
  },
  {
    id: "möda",
    word: "möda",
    options: ["tvång", "stress", "motgång", "tröghet", "ansträngning"],
    correct: 4,
    explanation: "Möda är den kraft och energi man lägger ner på något svårt.",
    source: "HT2025",
  },
  {
    id: "frekventera",
    word: "frekventera",
    options: ["besöka ofta", "variera", "justera noga", "gradera", "hålla koll på"],
    correct: 0,
    explanation: "Att frekventera en plats är att gå dit regelbundet.",
    source: "HT2025",
  },
  {
    id: "raffinemang",
    word: "raffinemang",
    options: ["överflöd", "förfining", "urskiljning", "komplikation", "uppskattning"],
    correct: 1,
    explanation: "Raffinemang står för finess och elegans, ofta i stil eller smak.",
    source: "HT2025",
  },
  {
    id: "i-paritet-med",
    word: "i paritet med",
    options: ["med hänsyn till", "samtidig med", "likvärdig med", "medskyldig till", "med hjälp av"],
    correct: 2,
    explanation: "Att vara i paritet med något är att ligga på samma nivå.",
    source: "HT2025",
  },
  {
    id: "gondol",
    word: "gondol",
    options: ["mur", "kärra", "torn", "båt", "kruka"],
    correct: 3,
    explanation: "En gondol är en smal, platt roddbåt, känd från Venedigs kanaler.",
    source: "HT2025",
  },
  {
    id: "obemedlad",
    word: "obemedlad",
    options: ["hemlös", "arbetslös", "ensam", "tanklös", "fattig"],
    correct: 4,
    explanation: "Obemedlad betyder att sakna pengar eller ekonomiska tillgångar.",
    source: "HT2025",
  },
  {
    id: "basal",
    word: "basal",
    options: ["grundläggande", "hållbar", "underförstådd", "vardaglig", "genomtänkt"],
    correct: 0,
    explanation: "Basal betyder att något ligger till grund för annat, är helt fundamentalt.",
    source: "VT2025",
  },
  {
    id: "defekt",
    word: "defekt",
    options: ["olycka", "brist", "obehag", "tröghet", "misstag"],
    correct: 1,
    explanation: "En defekt är ett fel eller en bristfällighet i något.",
    source: "VT2025",
  },
  {
    id: "länsa",
    word: "länsa",
    options: ["putsa", "fånga", "tömma", "lossa", "sänka"],
    correct: 2,
    explanation: "Att länsa något, t.ex. ett konto eller en brunn, är att tömma det helt.",
    source: "VT2025",
  },
  {
    id: "gensvar",
    word: "gensvar",
    options: ["reflektion", "påpekande", "klargörande", "respons", "upprepning"],
    correct: 3,
    explanation: "Gensvar är den reaktion eller det svar man får på något man gjort eller sagt.",
    source: "VT2025",
  },
  {
    id: "kontroversiell",
    word: "kontroversiell",
    options: ["obegriplig", "kritisk", "angelägen", "omdömeslös", "omtvistad"],
    correct: 4,
    explanation: "Kontroversiell betyder att väcka delade meningar och debatt.",
    source: "VT2025",
  },
  {
    id: "eskapader",
    word: "eskapader",
    options: ["äventyr", "hemligheter", "genvägar", "drömmar", "förklädnader"],
    correct: 0,
    explanation: "Eskapader är djärva, ofta lite oansvariga upptåg eller äventyr.",
    source: "VT2025",
  },
  {
    id: "förfoga-över",
    word: "förfoga över",
    options: ["ge", "ha", "byta", "ta", "få"],
    correct: 1,
    explanation: "Att förfoga över något är att ha rätt att bestämma över eller använda det.",
    source: "VT2025",
  },
  {
    id: "diger",
    word: "diger",
    options: ["härlig", "underlig", "stor", "djup", "smaklig"],
    correct: 2,
    explanation: "Diger används ofta om en omfattande mängd eller ett tjockt verk.",
    source: "VT2025",
  },
  {
    id: "aversion",
    word: "aversion",
    options: ["motsats", "bestämdhet", "förtvivlan", "motvilja", "besvikelse"],
    correct: 3,
    explanation: "Aversion är en stark ovilja eller avsky mot något.",
    source: "VT2025",
  },
  {
    id: "fåfängt",
    word: "fåfängt",
    options: ["energiskt", "sällsynt", "försiktigt", "imponerande", "resultatlöst"],
    correct: 4,
    explanation: "Fåfängt beskriver ett försök som inte leder någonstans, förgäves.",
    source: "VT2025",
  },
  {
    id: "olidlig",
    word: "olidlig",
    options: ["omöjlig att uthärda", "osannolik", "oanständig", "bekymmerslös", "svår att förstå"],
    correct: 0,
    explanation: "Olidlig betyder outhärdlig, till exempel om smärta eller väntan.",
    source: "VT2025",
  },
  {
    id: "återstoden",
    word: "återstoden",
    options: ["slutet", "resten", "minnet", "svaret", "reprisen"],
    correct: 1,
    explanation: "Återstoden är det som blir kvar när man tagit bort en del av något.",
    source: "VT2025",
  },
  {
    id: "klandervärt",
    word: "klandervärt",
    options: ["välgörande", "oskyldigt", "förkastligt", "otänkbart", "förvånande"],
    correct: 2,
    explanation: "Klandervärt betyder att förtjäna kritik, moraliskt tvivelaktigt.",
    source: "VT2025",
  },
  {
    id: "intervention",
    word: "intervention",
    options: ["avbrott", "stödfunktion", "förmedling", "ingripande", "inaktivitet"],
    correct: 3,
    explanation: "En intervention är ett aktivt ingripande i en situation, t.ex. i vårdsammanhang.",
    source: "VT2025",
  },
  {
    id: "bistå",
    word: "bistå",
    options: ["vakta", "hålla ihop", "närvara", "stanna kvar", "hjälpa"],
    correct: 4,
    explanation: "Att bistå någon är att ge stöd eller assistans.",
    source: "VT2025",
  },
  {
    id: "parafras",
    word: "parafras",
    options: ["omskrivning", "inledning", "förkortning", "överläggning", "utvidgning"],
    correct: 0,
    explanation: "En parafras återger innehållet i en text med andra ord.",
    source: "VT2025",
  },
  {
    id: "gedigen",
    word: "gedigen",
    options: ["konkret", "solid", "effektiv", "realistisk", "uppskattad"],
    correct: 1,
    explanation: "Gedigen betyder grundlig och pålitlig, ofta om kunskap eller hantverk.",
    source: "VT2025",
  },
  {
    id: "hålla-till-godo-med",
    word: "hålla till godo med",
    options: ["samtycka till", "förvänta sig", "nöja sig med", "roa sig med", "ge tillstånd till"],
    correct: 2,
    explanation: "Att hålla till godo med något är att acceptera det man har, även om det inte är optimalt.",
    source: "VT2025",
  },
  {
    id: "vånda",
    word: "vånda",
    options: ["avsmak", "uppgivenhet", "saknad", "ångest", "ansträngning"],
    correct: 3,
    explanation: "Vånda är ett starkt inre lidande eller kval.",
    source: "VT2025",
  },
  {
    id: "fingerad",
    word: "fingerad",
    options: ["fastställd", "praktisk", "berörd", "reserverad", "påhittad"],
    correct: 4,
    explanation: "Fingerad betyder påhittad eller iscensatt för att verka äkta.",
    source: "VT2025",
  },
  {
    id: "hysa-agg",
    word: "hysa agg",
    options: ["vara fientligt inställd", "vara spydig", "kritisera", "irritera", "göra någon illa"],
    correct: 0,
    explanation: "Att hysa agg mot någon är att bära på långvarig vrede eller motvilja.",
    source: "HT2024",
  },
  {
    id: "kontinuum",
    word: "kontinuum",
    options: ["upplösning", "obruten följd", "evigt liv", "motsatsförhållande", "förlängning"],
    correct: 1,
    explanation: "Ett kontinuum är en obruten, gradvis övergående helhet.",
    source: "HT2024",
  },
  {
    id: "vimmelkantig",
    word: "vimmelkantig",
    options: ["trött", "osäker", "yr", "klumpig", "hjälplös"],
    correct: 2,
    explanation: "Vimmelkantig betyder yr i huvudet, förvirrad av intryck.",
    source: "HT2024",
  },
  {
    id: "krill",
    word: "krill",
    options: ["korall", "sjögräs", "parasit", "kräftdjur", "grodyngel"],
    correct: 3,
    explanation: "Krill är små havslevande kräftdjur som är en viktig föda för valar.",
    source: "HT2024",
  },
  {
    id: "restriktiv",
    word: "restriktiv",
    options: ["bestämd", "ordentlig", "påfrestande", "motvillig", "återhållsam"],
    correct: 4,
    explanation: "Restriktiv betyder att man är sparsam eller begränsande i sitt tillåtande.",
    source: "HT2024",
  },
  {
    id: "särdrag",
    word: "särdrag",
    options: ["utmärkande egenskap", "avvikande åsikt", "skiljelinje", "klokt agerande", "diskriminering"],
    correct: 0,
    explanation: "Ett särdrag är något som gör en person eller sak unik.",
    source: "HT2024",
  },
  {
    id: "osökt",
    word: "osökt",
    options: ["rättvist", "naturligt", "intressant", "hoppfullt", "viktigt"],
    correct: 1,
    explanation: "Osökt betyder att något sker utan ansträngning, av sig självt.",
    source: "HT2024",
  },
  {
    id: "empati",
    word: "empati",
    options: ["hjälpsamhet", "uppskattning", "inlevelseförmåga", "tillgivenhet", "ömsesidighet"],
    correct: 2,
    explanation: "Empati är förmågan att leva sig in i och förstå andras känslor.",
    source: "HT2024",
  },
  {
    id: "bordlägga",
    word: "bordlägga",
    options: ["tilltala", "intyga", "motstå", "uppskjuta", "förevisa"],
    correct: 3,
    explanation: "Att bordlägga en fråga är att skjuta upp beslutet till senare.",
    source: "HT2024",
  },
  {
    id: "taktfull",
    word: "taktfull",
    options: ["snabb", "högljudd", "noggrann", "uthållig", "finkänslig"],
    correct: 4,
    explanation: "Taktfull betyder att vara varsam och hänsynsfull i hur man agerar.",
    source: "HT2024",
  },
  {
    id: "haverera",
    word: "haverera",
    options: ["gå sönder", "ge sig", "ta med sig", "dra ut på tiden", "jämnas ut"],
    correct: 0,
    explanation: "Att haverera är att kollapsa eller gå fullständigt sönder, t.ex. ett projekt.",
    source: "HT2024",
  },
  {
    id: "bestående",
    word: "bestående",
    options: ["fullständig", "permanent", "principfast", "ordinarie", "trovärdig"],
    correct: 1,
    explanation: "Bestående betyder att något varar över tid, inte tillfälligt.",
    source: "HT2024",
  },
  {
    id: "handräckning",
    word: "handräckning",
    options: ["ansträngning", "medgivande", "hjälp", "hänvisning", "tröst"],
    correct: 2,
    explanation: "Handräckning är praktisk hjälp, ofta i en akut eller officiell situation.",
    source: "HT2024",
  },
  {
    id: "sank",
    word: "sank",
    options: ["stenig", "gropig", "halkig", "sumpig", "risig"],
    correct: 3,
    explanation: "Sank mark är blöt och mjuk, nästan som en myr.",
    source: "HT2024",
  },
  {
    id: "mothugg",
    word: "mothugg",
    options: ["svårighet", "misslyckande", "spontan reflex", "förräderi", "häftig kritik"],
    correct: 4,
    explanation: "Mothugg är en skarp motreaktion eller kritik mot något som sagts.",
    source: "HT2024",
  },
  {
    id: "händelsevis",
    word: "händelsevis",
    options: ["av en tillfällighet", "helt plötsligt", "upprepade gånger", "i tur och ordning", "då och då"],
    correct: 0,
    explanation: "Händelsevis betyder av en slump, oavsiktligt.",
    source: "HT2024",
  },
  {
    id: "spänst",
    word: "spänst",
    options: ["uthållighet", "styrka och smidighet", "följsamhet", "balans och kontroll", "snabbhet"],
    correct: 1,
    explanation: "Spänst är kroppens förmåga till snabb, kraftfull rörelse.",
    source: "HT2024",
  },
  {
    id: "porös",
    word: "porös",
    options: ["uttorkad", "innehållslös", "genomsläpplig", "kompakt", "fjädrande"],
    correct: 2,
    explanation: "Poröst material har små hål som släpper igenom vätska eller luft.",
    source: "HT2024",
  },
  {
    id: "soliditet",
    word: "soliditet",
    options: ["god hälsa", "rationell lösning", "orsakssamband", "finansiell stabilitet", "styrkedemonstration"],
    correct: 3,
    explanation: "Soliditet mäter hur stabil en verksamhets ekonomi är.",
    source: "HT2024",
  },
  {
    id: "förlora-målföret",
    word: "förlora målföret",
    options: ["ge upp", "gå vilse", "hamna efter", "mista förståndet", "bli mållös"],
    correct: 4,
    explanation: "Att förlora målföret är att bli så överraskad att man inte kan tala.",
    source: "HT2024",
  },
  {
    id: "dispyt",
    word: "dispyt",
    options: ["gräl", "brist", "tvekan", "besvikelse", "undantag"],
    correct: 0,
    explanation: "En dispyt är en tvist eller meningsskiljaktighet mellan parter.",
    source: "VT2024",
  },
  {
    id: "angeläget",
    word: "angeläget",
    options: ["tydligt", "viktigt", "utmanande", "informativt", "noggrant"],
    correct: 1,
    explanation: "Angeläget betyder brådskande viktigt, något som kräver uppmärksamhet.",
    source: "VT2024",
  },
  {
    id: "supplement",
    word: "supplement",
    options: ["överskott", "urval", "tillägg", "innehåll", "understöd"],
    correct: 2,
    explanation: "Ett supplement kompletterar något som redan finns.",
    source: "VT2024",
  },
  {
    id: "aktad",
    word: "aktad",
    options: ["högtidlig", "artig", "försiktig", "respekterad", "undanskymd"],
    correct: 3,
    explanation: "Aktad betyder att åtnjuta stor respekt och aktning.",
    source: "VT2024",
  },
  {
    id: "rata",
    word: "rata",
    options: ["granska", "fastställa", "ifrågasätta", "samordna", "avvisa"],
    correct: 4,
    explanation: "Att rata något är att bestämt välja bort det.",
    source: "VT2024",
  },
  {
    id: "illa-åtgången",
    word: "illa åtgången",
    options: ["svårt angripen", "helt uttorkad", "nästan slut", "mycket ledsen", "lämnad utanför"],
    correct: 0,
    explanation: "Illa åtgången betyder svårt skadad eller medtagen.",
    source: "VT2024",
  },
  {
    id: "bärkraft",
    word: "bärkraft",
    options: ["avlagring", "hållbarhet", "prestation", "tryck", "försörjning"],
    correct: 1,
    explanation: "Bärkraft är förmågan att hålla över tid utan att kollapsa.",
    source: "VT2024",
  },
  {
    id: "vegetera",
    word: "vegetera",
    options: ["tala gåtfullt", "vara generös", "leva i overksamhet", "besvära i onödan", "sprida oro"],
    correct: 2,
    explanation: "Att vegetera är att passivt låta tiden gå utan att göra något.",
    source: "VT2024",
  },
  {
    id: "egalitär",
    word: "egalitär",
    options: ["tillfällig", "obekymrad", "välvillig", "jämlik", "ursprunglig"],
    correct: 3,
    explanation: "Egalitär betyder att sträva efter jämlikhet mellan människor.",
    source: "VT2024",
  },
  {
    id: "kavalkad",
    word: "kavalkad",
    options: ["kort historia", "utvald grupp", "tapper skara", "begränsad mängd", "lång rad"],
    correct: 4,
    explanation: "En kavalkad är en lång följd av företeelser eller händelser i procession.",
    source: "VT2024",
  },
  {
    id: "försegla",
    word: "försegla",
    options: ["tillsluta", "upphöra", "undersöka", "avgöra", "omringa"],
    correct: 0,
    explanation: "Att försegla något är att stänga det helt och hållet, ofta officiellt.",
    source: "VT2024",
  },
  {
    id: "autodidakt",
    word: "autodidakt",
    options: ["pålitlig person", "självlärd person", "mäktig person", "egoistisk person", "inbunden person"],
    correct: 1,
    explanation: "En autodidakt har lärt sig sina kunskaper på egen hand, utan formell utbildning.",
    source: "VT2024",
  },
  {
    id: "gentemot",
    word: "gentemot",
    options: ["nära intill", "bortsett från", "i förhållande till", "som alternativ till", "med tanke på"],
    correct: 2,
    explanation: "Gentemot används för att jämföra eller ställa något mot något annat.",
    source: "VT2024",
  },
  {
    id: "utarmad",
    word: "utarmad",
    options: ["fri", "farlig", "förlamad", "fattig", "feg"],
    correct: 3,
    explanation: "Utarmad betyder att ha förlorat sina resurser eller sin näring.",
    source: "VT2024",
  },
  {
    id: "axplock",
    word: "axplock",
    options: ["enformigt arbete", "förstahandsval", "kvalificerad gissning", "stor noggrannhet", "slumpartat urval"],
    correct: 4,
    explanation: "Ett axplock är ett litet, representativt urval ur en större mängd.",
    source: "VT2024",
  },
  {
    id: "exceptionell",
    word: "exceptionell",
    options: ["sällsynt", "nyanserad", "högtidlig", "överdriven", "uttrycksfull"],
    correct: 0,
    explanation: "Exceptionell betyder utomordentlig, långt över det vanliga.",
    source: "VT2024",
  },
  {
    id: "tillkännage",
    word: "tillkännage",
    options: ["anropa", "meddela", "besvara", "instämma", "efterfråga"],
    correct: 1,
    explanation: "Att tillkännage något är att offentligt informera om det.",
    source: "VT2024",
  },
  {
    id: "appell",
    word: "appell",
    options: ["löfte", "misstanke", "vädjan", "övertygelse", "intryck"],
    correct: 2,
    explanation: "En appell är en känsloladdad uppmaning eller begäran.",
    source: "VT2024",
  },
  {
    id: "intrikat",
    word: "intrikat",
    options: ["intensiv", "inställsam", "intressant", "invecklad", "inåtvänd"],
    correct: 3,
    explanation: "Intrikat betyder komplicerad och svår att reda ut.",
    source: "VT2024",
  },
  {
    id: "debacle",
    word: "debacle",
    options: ["klarhet", "omröstning", "tillfällighet", "förbättring", "misslyckande"],
    correct: 4,
    explanation: "Ett debacle är ett spektakulärt och pinsamt misslyckande.",
    source: "VT2024",
  },
  {
    id: "proper",
    word: "proper",
    options: ["välvårdad", "stolt", "måttfull", "allvarlig", "förmögen"],
    correct: 0,
    explanation: "Proper betyder prydlig och ordentlig i sitt yttre.",
    source: "HT2023",
  },
  {
    id: "galosch",
    word: "galosch",
    options: ["filthatt", "gummisko", "slipsnål", "högtidsdräkt", "slängkappa"],
    correct: 1,
    explanation: "En galosch är en vattentät sko man drar utanpå den vanliga skon.",
    source: "HT2023",
  },
  {
    id: "dementera",
    word: "dementera",
    options: ["sörja", "ljuga", "förneka", "förbjuda", "störa"],
    correct: 2,
    explanation: "Att dementera ett påstående är att officiellt förklara att det är felaktigt.",
    source: "HT2023",
  },
  {
    id: "medaljens-baksida",
    word: "medaljens baksida",
    options: ["orsaken", "undantaget", "motståndet", "nackdelen", "resultatet"],
    correct: 3,
    explanation: "Medaljens baksida syftar på den mindre positiva sidan av något gott.",
    source: "HT2023",
  },
  {
    id: "cerebral",
    word: "cerebral",
    options: ["som orsakar smärta", "som rör synen", "som beror på kosten", "som sker reflexmässigt", "som gäller hjärnan"],
    correct: 4,
    explanation: "Cerebral relaterar till hjärnan, ofta i betydelsen intellektuell.",
    source: "HT2023",
  },
  {
    id: "hemsökelse",
    word: "hemsökelse",
    options: ["utbredd plåga", "rastlöshet", "formell begäran", "uppståndelse", "personligt erbjudande"],
    correct: 0,
    explanation: "Hemsökelse är en svår och långvarig prövning som drabbar många.",
    source: "HT2023",
  },
  {
    id: "tjänlig",
    word: "tjänlig",
    options: ["lärorik", "användbar", "begriplig", "tillgänglig", "lättskött"],
    correct: 1,
    explanation: "Tjänlig betyder lämplig eller dugande för ett visst ändamål.",
    source: "HT2023",
  },
  {
    id: "vara-avhängig-av",
    word: "vara avhängig av",
    options: ["stå ut med", "räknas in i", "bero på", "utsättas för", "ha tilltro till"],
    correct: 2,
    explanation: "Att vara avhängig av något är att vara beroende av det.",
    source: "HT2023",
  },
  {
    id: "klander",
    word: "klander",
    options: ["orimligt antagande", "osann uppgift", "omild behandling", "ogillande anmärkning", "olyckligt misstag"],
    correct: 3,
    explanation: "Klander är kritik som riktas mot någons handlande.",
    source: "HT2023",
  },
  {
    id: "omsorgsfull",
    word: "omsorgsfull",
    options: ["trevlig", "bekymrad", "tankfull", "inställsam", "noggrann"],
    correct: 4,
    explanation: "Omsorgsfull betyder att utföra något med stor omtanke och noggrannhet.",
    source: "HT2023",
  },
  {
    id: "löpa-amok",
    word: "löpa amok",
    options: ["få raserianfall", "gå vilse", "vara försenad", "bli överlycklig", "ramla omkull"],
    correct: 0,
    explanation: "Att löpa amok är att i ursinne tappa all kontroll.",
    source: "HT2023",
  },
  {
    id: "påtaglig",
    word: "påtaglig",
    options: ["bekant", "märkbar", "särskild", "passande", "hastig"],
    correct: 1,
    explanation: "Påtaglig betyder tydligt kännbar eller synlig.",
    source: "HT2023",
  },
  {
    id: "uppsåtligen",
    word: "uppsåtligen",
    options: ["av välvilja", "i förtroende", "med avsikt", "på rätt sätt", "utan tvekan"],
    correct: 2,
    explanation: "Uppsåtligen betyder medvetet och avsiktligt, ofta i juridiska sammanhang.",
    source: "HT2023",
  },
  {
    id: "biopsi",
    word: "biopsi",
    options: ["blodgivning", "ärrbildning", "röntgenbild", "vävnadsprov", "transplantation"],
    correct: 3,
    explanation: "En biopsi är ett vävnadsprov som tas för undersökning.",
    source: "HT2023",
  },
  {
    id: "detronisera",
    word: "detronisera",
    options: ["utmana", "förakta", "avböja", "utvisa", "avsätta"],
    correct: 4,
    explanation: "Att detronisera någon är att beröva dem makten, avsätta en härskare.",
    source: "HT2023",
  },
  {
    id: "fruktlös",
    word: "fruktlös",
    options: ["som inte ger resultat", "mager", "utan innehåll", "utan anledning", "ofullständig"],
    correct: 0,
    explanation: "Fruktlös betyder resultatlös, utan framgång.",
    source: "HT2023",
  },
  {
    id: "kvintessensen",
    word: "kvintessensen",
    options: ["medelvägen", "det väsentliga", "det synliga", "den större delen", "avbildningen"],
    correct: 1,
    explanation: "Kvintessensen är kärnan eller det viktigaste i något.",
    source: "HT2023",
  },
  {
    id: "enveten",
    word: "enveten",
    options: ["exakt", "erfaren", "envis", "egoistisk", "enkelriktad"],
    correct: 2,
    explanation: "Enveten betyder ihärdigt bestämd, ovillig att ge sig.",
    source: "HT2023",
  },
  {
    id: "ombesörja",
    word: "ombesörja",
    options: ["ångra", "tillåta", "tvivla", "ordna", "upprepa"],
    correct: 3,
    explanation: "Att ombesörja något är att se till att det blir gjort.",
    source: "HT2023",
  },
  {
    id: "ingivelse",
    word: "ingivelse",
    options: ["oväntad gåva", "tillfällig lättnad", "snabb förändring", "positivt besked", "plötslig impuls"],
    correct: 4,
    explanation: "En ingivelse är en spontan känsla eller idé som dyker upp.",
    source: "HT2023",
  },
  {
    id: "förespråka",
    word: "förespråka",
    options: ["rekommendera", "reflektera", "reservera", "resonera", "regissera"],
    correct: 0,
    explanation: "Att förespråka något är att argumentera för och stödja det.",
    source: "VT2023",
  },
  {
    id: "obefogad",
    word: "obefogad",
    options: ["maktlös", "grundlös", "ansvarslös", "gränslös", "meningslös"],
    correct: 1,
    explanation: "Obefogad betyder omotiverad, utan giltiga skäl.",
    source: "VT2023",
  },
  {
    id: "emballage",
    word: "emballage",
    options: ["symbol", "underhåll", "förpackning", "avspärrning", "handelsförbud"],
    correct: 2,
    explanation: "Emballage är materialet som skyddar en vara vid transport och förvaring.",
    source: "VT2023",
  },
  {
    id: "tidvis",
    word: "tidvis",
    options: ["ofta", "förut", "punktligt", "ibland", "numera"],
    correct: 3,
    explanation: "Tidvis betyder vid vissa tider, med jämna mellanrum.",
    source: "VT2023",
  },
  {
    id: "framfusig",
    word: "framfusig",
    options: ["nytänkande", "självsäker", "uppjagad", "förväntansfull", "påträngande"],
    correct: 4,
    explanation: "Framfusig betyder att uppträda oförskämt eller pockande.",
    source: "VT2023",
  },
  {
    id: "extravagans",
    word: "extravagans",
    options: ["överdåd", "värdighet", "merkostnad", "passion", "övermod"],
    correct: 0,
    explanation: "Extravagans är ett flärdfullt, kostsamt sätt att leva eller uppträda.",
    source: "VT2023",
  },
  {
    id: "ge-sig-till-tåls",
    word: "ge sig till tåls",
    options: ["ta sitt ansvar", "lugnt invänta något", "vara i underläge", "fatta ett beslut", "visa sin styrka"],
    correct: 1,
    explanation: "Att ge sig till tåls är att tålmodigt vänta ut något.",
    source: "VT2023",
  },
  {
    id: "baryton",
    word: "baryton",
    options: ["notställ", "pianostycke", "röstläge", "slagverkare", "taktpinne"],
    correct: 2,
    explanation: "Baryton är ett manligt sångröstläge mellan tenor och bas.",
    source: "VT2023",
  },
  {
    id: "rågad",
    word: "rågad",
    options: ["kraftig", "bristfällig", "åtgärdad", "överfull", "avslutad"],
    correct: 3,
    explanation: "Rågad betyder fylld till brädden, mer än full.",
    source: "VT2023",
  },
  {
    id: "maxim",
    word: "maxim",
    options: ["reaktion", "jämvikt", "slutresultat", "förbindelse", "levnadsregel"],
    correct: 4,
    explanation: "En maxim är en kort, allmänt vedertagen livsregel eller sanning.",
    source: "VT2023",
  },
  {
    id: "ihärdig",
    word: "ihärdig",
    options: ["envis och uthållig", "snabb och explosiv", "hård och okänslig", "ivrig och hoppfull", "erfaren och duktig"],
    correct: 0,
    explanation: "Ihärdig betyder att fortsätta trots motstånd, envist uthållig.",
    source: "VT2023",
  },
  {
    id: "hereditet",
    word: "hereditet",
    options: ["ensamhet", "ärftlighet", "vänlighet", "fromhet", "sjuklighet"],
    correct: 1,
    explanation: "Hereditet är läran om och förekomsten av arv mellan generationer.",
    source: "VT2023",
  },
  {
    id: "begrunda",
    word: "begrunda",
    options: ["tillägna sig", "instämma i", "fundera på", "ta itu med", "besluta sig för"],
    correct: 2,
    explanation: "Att begrunda något är att tänka igenom det noggrant.",
    source: "VT2023",
  },
  {
    id: "klädsam",
    word: "klädsam",
    options: ["blyg", "ytlig", "modern", "passande", "enkel"],
    correct: 3,
    explanation: "Klädsam betyder att klä eller passa någon väl.",
    source: "VT2023",
  },
  {
    id: "med-nöd-och-näppe",
    word: "med nöd och näppe",
    options: ["av tvång", "till slut", "på pricken", "utan problem", "nästan inte"],
    correct: 4,
    explanation: "Med nöd och näppe betyder att något lyckades precis, med minsta marginal.",
    source: "VT2023",
  },
  {
    id: "utfall",
    word: "utfall",
    options: ["resultat", "minskning", "avvikelse", "sannolikhet", "överskott"],
    correct: 0,
    explanation: "Utfall är resultatet eller effekten av en handling eller process.",
    source: "VT2023",
  },
  {
    id: "cementera",
    word: "cementera",
    options: ["slutföra", "göra beständig", "jämna till", "göra avtryck", "stänga inne"],
    correct: 1,
    explanation: "Att cementera något är att befästa och göra det bestående.",
    source: "VT2023",
  },
  {
    id: "trollbunden",
    word: "trollbunden",
    options: ["inbillad", "grundlurad", "fascinerad", "förvirrad", "överraskad"],
    correct: 2,
    explanation: "Trollbunden betyder helt fångad av intresse eller förundran.",
    source: "VT2023",
  },
  {
    id: "lasyr",
    word: "lasyr",
    options: ["finslipad yta", "stilfull dekoration", "oönskad beläggning", "genomskinlig färg", "förgrenat mönster"],
    correct: 3,
    explanation: "Lasyr är ett tunt, genomskinligt färgskikt som används i måleri.",
    source: "VT2023",
  },
  {
    id: "vag",
    word: "vag",
    options: ["avlägsen", "betydelselös", "tillfällig", "ostadig", "obestämd"],
    correct: 4,
    explanation: "Vag betyder oklar och diffus, svår att precisera.",
    source: "VT2023",
  },
  {
    id: "signifikans",
    word: "signifikans",
    options: ["betydelse", "undantag", "skillnad", "måluppfyllelse", "uppfattning"],
    correct: 0,
    explanation: "Signifikans anger hur betydelsefullt eller statistiskt säkerställt ett resultat är.",
    source: "HT2022",
  },
  {
    id: "blottlagd",
    word: "blottlagd",
    options: ["känslosam", "synliggjord", "värdelös", "övergiven", "undanröjd"],
    correct: 1,
    explanation: "Blottlagd betyder friläggd eller avslöjad, gjord synlig.",
    source: "HT2022",
  },
  {
    id: "mitos",
    word: "mitos",
    options: ["uttorkning", "blödning", "celldelning", "sårläkning", "befruktning"],
    correct: 2,
    explanation: "Mitos är den process där en cell delar sig i två identiska celler.",
    source: "HT2022",
  },
  {
    id: "revidera",
    word: "revidera",
    options: ["påpeka", "hindra", "ersätta", "ändra", "förneka"],
    correct: 3,
    explanation: "Att revidera något är att granska och göra ändringar i det.",
    source: "HT2022",
  },
  {
    id: "heterogen",
    word: "heterogen",
    options: ["hållbar", "i fast form", "naturell", "dubbelsidig", "olikartad"],
    correct: 4,
    explanation: "Heterogen betyder sammansatt av olika, blandade delar.",
    source: "HT2022",
  },
  {
    id: "framsynthet",
    word: "framsynthet",
    options: ["förutseende", "förhoppning", "upplysning", "övertygelse", "utveckling"],
    correct: 0,
    explanation: "Framsynthet är förmågan att förutse framtida behov eller händelser.",
    source: "HT2022",
  },
  {
    id: "blidka",
    word: "blidka",
    options: ["ångra sig bittert", "göra mer vänligt inställd", "lämna i fred", "inge förtroende", "be om en tjänst"],
    correct: 1,
    explanation: "Att blidka någon är att lugna deras vrede genom vänligt bemötande.",
    source: "HT2022",
  },
  {
    id: "galax",
    word: "galax",
    options: ["himlakropp", "spiralform", "stjärnsystem", "tidsrymd", "planetformation"],
    correct: 2,
    explanation: "En galax är ett enormt system av stjärnor, gas och stoft.",
    source: "HT2022",
  },
  {
    id: "modest",
    word: "modest",
    options: ["snäll", "pålitlig", "utmanande", "blygsam", "populär"],
    correct: 3,
    explanation: "Modest betyder anspråkslös, utan skryt.",
    source: "HT2022",
  },
  {
    id: "som-en-osalig-ande",
    word: "som en osalig ande",
    options: ["naiv och godtrogen", "sviken och olycklig", "hård och känslokall", "hatisk och hämndlysten", "orolig och rastlös"],
    correct: 4,
    explanation: "Uttrycket beskriver någon som vandrar rastlöst, utan ro, likt ett spöke.",
    source: "HT2022",
  },
  {
    id: "inhemsk",
    word: "inhemsk",
    options: ["som hör till det egna landet", "som har vissa brister", "som uppskattas av många", "som kan verka obehaglig", "som har använts tidigare"],
    correct: 0,
    explanation: "Inhemsk betyder inrikes, tillhörande det egna landet.",
    source: "HT2022",
  },
  {
    id: "mantra",
    word: "mantra",
    options: ["bibelcitat", "meditationsformel", "takmålning", "lyckoamulett", "symmetrisk bild"],
    correct: 1,
    explanation: "Ett mantra är en fras eller ett ljud som upprepas vid meditation.",
    source: "HT2022",
  },
  {
    id: "fördärva",
    word: "fördärva",
    options: ["förbruka", "förfalska", "förstöra", "förkasta", "förnedra"],
    correct: 2,
    explanation: "Att fördärva något är att skada det så att det blir odugligt.",
    source: "HT2022",
  },
  {
    id: "utan-pardon",
    word: "utan pardon",
    options: ["utan tröst", "utan hjälp", "utan skydd", "utan nåd", "utan tvivel"],
    correct: 3,
    explanation: "Utan pardon betyder skoningslöst, utan förbarmande.",
    source: "HT2022",
  },
  {
    id: "terapeutisk",
    word: "terapeutisk",
    options: ["beskrivande", "lätthanterlig", "förebyggande", "långsiktig", "läkande"],
    correct: 4,
    explanation: "Terapeutisk syftar på något som har en läkande eller lindrande effekt.",
    source: "HT2022",
  },
  {
    id: "avsteg",
    word: "avsteg",
    options: ["mindre avvikelse", "stort misstag", "olyckshändelse", "helomvändning", "oväntat beslut"],
    correct: 0,
    explanation: "Ett avsteg är att man avviker något från en regel eller plan.",
    source: "HT2022",
  },
  {
    id: "gravt",
    word: "gravt",
    options: ["ödsligt", "allvarligt", "skenbart", "knappt", "dolt"],
    correct: 1,
    explanation: "Gravt förstärker ofta ett negativt tillstånd, t.ex. gravt handikappad.",
    source: "HT2022",
  },
  {
    id: "enträgen",
    word: "enträgen",
    options: ["naiv", "grinig", "outtröttlig", "självisk", "eftertänksam"],
    correct: 2,
    explanation: "Enträgen betyder ihärdigt och bestämt bedjande, som inte ger upp.",
    source: "HT2022",
  },
  {
    id: "antipati",
    word: "antipati",
    options: ["motsats", "motgång", "motkraft", "motvilja", "motsägelse"],
    correct: 3,
    explanation: "Antipati är en stark ogillande känsla mot någon eller något.",
    source: "HT2022",
  },
  {
    id: "raljera",
    word: "raljera",
    options: ["visa intresse", "blanda ihop", "granska noga", "skära upp", "skämta ironiskt"],
    correct: 4,
    explanation: "Att raljera är att göra sig lustig över något på ett lätt hånfullt sätt.",
    source: "HT2022",
  },
  {
    id: "abstinens",
    word: "abstinens",
    options: ["kroppsliga besvär vid avvänjning", "ökad aptit", "plötslig eufori", "djup sömn", "förhöjd puls av glädje"],
    correct: 0,
    explanation: "Abstinens är de fysiska och psykiska besvär som uppstår när man slutar med t.ex. ett beroendeframkallande ämne.",
    source: "egen (HP-typ)",
  },
  {
    id: "adekvat",
    word: "adekvat",
    options: ["överdrivet komplicerad", "lämplig för ändamålet", "svårbegriplig", "kostsam", "föråldrad"],
    correct: 1,
    explanation: "Adekvat betyder att något passar precis för sitt syfte.",
    source: "egen (HP-typ)",
  },
  {
    id: "affekterad",
    word: "affekterad",
    options: ["äkta och spontan", "sansad och lugn", "onaturligt tillgjord", "blyg och tillbakadragen", "otydlig i sitt tal"],
    correct: 2,
    explanation: "Affekterad beskriver ett tillgjort, överdrivet sätt att uttrycka sig.",
    source: "egen (HP-typ)",
  },
  {
    id: "akribi",
    word: "akribi",
    options: ["snabb improvisation", "personlig övertygelse", "praktisk erfarenhet", "vetenskaplig noggrannhet", "muntlig tradition"],
    correct: 3,
    explanation: "Akribi står för stor noggrannhet, särskilt i vetenskapligt arbete.",
    source: "egen (HP-typ)",
  },
  {
    id: "allehanda",
    word: "allehanda",
    options: ["av ett enda slag", "i stor mängd", "i liten mängd", "sällan förekommande", "av olika slag"],
    correct: 4,
    explanation: "Allehanda betyder blandat, av många olika sorter.",
    source: "egen (HP-typ)",
  },
  {
    id: "altruism",
    word: "altruism",
    options: ["osjälviskt hjälpande", "strategiskt beräknande", "avundsjuk jämförelse", "likgiltig hållning", "aggressivt hävdande"],
    correct: 0,
    explanation: "Altruism innebär att handla till andras fördel utan tanke på egen vinning.",
    source: "egen (HP-typ)",
  },
  {
    id: "ambivalent",
    word: "ambivalent",
    options: ["helt övertygad", "delad i sin inställning", "likgiltig", "aggressivt avvisande", "entusiastiskt positiv"],
    correct: 1,
    explanation: "Ambivalent betyder att känna motstridiga känslor inför samma sak.",
    source: "egen (HP-typ)",
  },
  {
    id: "anakronism",
    word: "anakronism",
    options: ["upprepad händelse", "logisk motsägelse", "tidsförskjuten företeelse", "kortlivad trend", "geografisk avvikelse"],
    correct: 2,
    explanation: "En anakronism är något som hör till fel tidsperiod, t.ex. en klocka i en medeltidsfilm.",
    source: "egen (HP-typ)",
  },
  {
    id: "anhang",
    word: "anhang",
    options: ["formell ansökan", "tillfällig lösning", "juridiskt dokument", "krets av anhängare", "hemlig plan"],
    correct: 3,
    explanation: "Anhang syftar på personer som följer eller stödjer någon.",
    source: "egen (HP-typ)",
  },
  {
    id: "animositet",
    word: "animositet",
    options: ["djup beundran", "likgiltig neutralitet", "stark entusiasm", "vänskaplig omtanke", "fientlig inställning"],
    correct: 4,
    explanation: "Animositet är en uttalad ovilja eller fientlighet mot någon.",
    source: "egen (HP-typ)",
  },
  {
    id: "anspråksfull",
    word: "anspråksfull",
    options: ["som ställer höga krav", "blygsam", "oengagerad", "tillmötesgående", "obekymrad"],
    correct: 0,
    explanation: "Anspråksfull betyder att kräva eller förvänta sig mycket.",
    source: "egen (HP-typ)",
  },
  {
    id: "antecipera",
    word: "antecipera",
    options: ["förklara i efterhand", "förutse", "sammanfatta kort", "kritisera hårt", "avfärda helt"],
    correct: 1,
    explanation: "Att antecipera något är att räkna med det innan det händer.",
    source: "egen (HP-typ)",
  },
  {
    id: "antites",
    word: "antites",
    options: ["förstärkning av en tes", "upprepning av ett argument", "motsats i ett resonemang", "sammanfattning av en debatt", "bevis för en teori"],
    correct: 2,
    explanation: "En antites ställer en motsatt ståndpunkt mot en tidigare tes.",
    source: "egen (HP-typ)",
  },
  {
    id: "apati",
    word: "apati",
    options: ["stark entusiasm", "plötslig ilska", "djup sorg", "känslomässig likgiltighet", "överdriven optimism"],
    correct: 3,
    explanation: "Apati innebär avsaknad av engagemang eller känsloreaktion.",
    source: "egen (HP-typ)",
  },
  {
    id: "arbiträr",
    word: "arbiträr",
    options: ["väl underbyggd", "konsekvent tillämpad", "vetenskapligt bevisad", "allmänt accepterad", "godtycklig"],
    correct: 4,
    explanation: "Arbiträr betyder att något bestäms utan tydlig logisk grund.",
    source: "egen (HP-typ)",
  },
  {
    id: "arkaisk",
    word: "arkaisk",
    options: ["ålderdomlig", "nyskapande", "tillfällig", "praktisk", "populär"],
    correct: 0,
    explanation: "Arkaisk beskriver något som tillhör en svunnen tid, omodernt.",
    source: "egen (HP-typ)",
  },
  {
    id: "artificiell",
    word: "artificiell",
    options: ["naturlig", "konstgjord", "spontan", "genuin", "slumpmässig"],
    correct: 1,
    explanation: "Artificiell betyder tillverkad av människan, inte naturligt uppkommen.",
    source: "egen (HP-typ)",
  },
  {
    id: "asymmetrisk",
    word: "asymmetrisk",
    options: ["exakt spegelvänd", "perfekt symmetrisk", "olikformad på ömse sidor", "geometriskt regelbunden", "jämnt fördelad"],
    correct: 2,
    explanation: "Asymmetrisk betyder att de två sidorna av något inte överensstämmer.",
    source: "egen (HP-typ)",
  },
  {
    id: "auktoritär",
    word: "auktoritär",
    options: ["eftergiven", "rådgivande", "demokratisk", "maktfullkomlig", "återhållsam"],
    correct: 3,
    explanation: "Auktoritär betyder att styra med hård hand och kräva lydnad.",
    source: "egen (HP-typ)",
  },
  {
    id: "avantgardistisk",
    word: "avantgardistisk",
    options: ["konservativ i sin form", "traditionsbunden", "populistisk", "kommersiellt inriktad", "banbrytande inom konsten"],
    correct: 4,
    explanation: "Avantgardistisk syftar på det mest nyskapande och experimentella inom en konstform.",
    source: "egen (HP-typ)",
  },
  {
    id: "avoghet",
    word: "avoghet",
    options: ["ovänligt bemötande", "hjärtlig gästfrihet", "stort tålamod", "genuin nyfikenhet", "lugn eftertänksamhet"],
    correct: 0,
    explanation: "Avoghet är ett kyligt, ovänligt sätt att bemöta någon.",
    source: "egen (HP-typ)",
  },
  {
    id: "axiom",
    word: "axiom",
    options: ["motbevisad teori", "grundsats utan bevis", "tillfällig slutsats", "osäker gissning", "empirisk observation"],
    correct: 1,
    explanation: "Ett axiom är ett påstående som tas för givet, utan att behöva bevisas.",
    source: "egen (HP-typ)",
  },
  {
    id: "banal",
    word: "banal",
    options: ["djupsinnig", "originell", "alldaglig och ointressant", "chockerande", "svårtydd"],
    correct: 2,
    explanation: "Banal betyder utnött och föga tankeväckande.",
    source: "egen (HP-typ)",
  },
  {
    id: "behjärtansvärd",
    word: "behjärtansvärd",
    options: ["tvivelaktig", "olönsam", "riskabel", "värd att stödja", "onödig"],
    correct: 3,
    explanation: "Behjärtansvärd beskriver ett syfte som är gott och förtjänar stöd.",
    source: "egen (HP-typ)",
  },
  {
    id: "benägen",
    word: "benägen",
    options: ["helt ovillig", "likgiltig inför", "omedveten om", "tveksam till", "böjd att göra något"],
    correct: 4,
    explanation: "Benägen betyder att ha en tendens eller lutning åt visst håll.",
    source: "egen (HP-typ)",
  },
  {
    id: "betänksam",
    word: "betänksam",
    options: ["eftertänksam och tveksam", "obetänksam och hastig", "säker och beslutsam", "likgiltig och passiv", "aggressiv och otålig"],
    correct: 0,
    explanation: "Betänksam betyder att fundera noga innan man agerar.",
    source: "egen (HP-typ)",
  },
  {
    id: "bigott",
    word: "bigott",
    options: ["öppensinnad", "trångsynt i sin tro", "tvivlande", "likgiltig", "vetgirig"],
    correct: 1,
    explanation: "Bigott beskriver en person med snäv, självrättfärdig övertygelse.",
    source: "egen (HP-typ)",
  },
  {
    id: "bisarr",
    word: "bisarr",
    options: ["förutsägbar", "vardaglig", "besynnerlig", "harmonisk", "traditionell"],
    correct: 2,
    explanation: "Bisarr betyder märklig och avvikande på ett iögonfallande sätt.",
    source: "egen (HP-typ)",
  },
  {
    id: "blaserad",
    word: "blaserad",
    options: ["nyfiken och entusiastisk", "chockad och upprörd", "orolig och ängslig", "utlevad och oberörbar", "naiv och godtrogen"],
    correct: 3,
    explanation: "Blaserad beskriver någon som blivit likgiltig genom att ha upplevt för mycket.",
    source: "egen (HP-typ)",
  },
  {
    id: "bornerad",
    word: "bornerad",
    options: ["vidsynt", "flexibel", "kunnig", "modig", "inskränkt i sitt tänkande"],
    correct: 4,
    explanation: "Bornerad betyder trångsynt och ovillig att ta in nya idéer.",
    source: "egen (HP-typ)",
  },
  {
    id: "brådmogen",
    word: "brådmogen",
    options: ["mogen i förtid", "sen i sin utveckling", "ovanligt barnslig", "extremt försiktig", "ointresserad av lärande"],
    correct: 0,
    explanation: "Brådmogen beskriver ett barn som utvecklas snabbare än förväntat.",
    source: "egen (HP-typ)",
  },
  {
    id: "bräcklig",
    word: "bräcklig",
    options: ["extremt tålig", "lätt att skada", "svårförstörbar", "kompakt", "flexibel"],
    correct: 1,
    explanation: "Bräcklig betyder ömtålig, lätt att gå sönder.",
    source: "egen (HP-typ)",
  },
  {
    id: "burdus",
    word: "burdus",
    options: ["diplomatisk", "försynt", "brysk och rättfram", "eftergiven", "reserverad"],
    correct: 2,
    explanation: "Burdus betyder ohövligt rakt på sak, utan finkänslighet.",
    source: "egen (HP-typ)",
  },
  {
    id: "charlatan",
    word: "charlatan",
    options: ["hedervärd forskare", "erfaren hantverkare", "blygsam amatör", "bedragare som ger sig ut för expert", "trogen assistent"],
    correct: 3,
    explanation: "En charlatan låtsas ha kunskaper eller förmågor denne saknar.",
    source: "egen (HP-typ)",
  },
  {
    id: "chikan",
    word: "chikan",
    options: ["hedersbetygelse", "uppmuntran", "belöning", "kompromiss", "trakasseri"],
    correct: 4,
    explanation: "Chikan är ett elakt, syftande till att förarga eller förnedra.",
    source: "egen (HP-typ)",
  },
  {
    id: "cynisk",
    word: "cynisk",
    options: ["misstroget nedvärderande", "godtrogen", "entusiastisk", "hoppfull", "naiv"],
    correct: 0,
    explanation: "Cynisk betyder att tvivla på andras goda avsikter.",
    source: "egen (HP-typ)",
  },
  {
    id: "dekadent",
    word: "dekadent",
    options: ["strängt återhållsam", "moraliskt förfallen i sin lyx", "flitig och sparsam", "enkel och anspråkslös", "idealistisk"],
    correct: 1,
    explanation: "Dekadent beskriver ett överdådigt leverne präglat av förfall.",
    source: "egen (HP-typ)",
  },
  {
    id: "demagog",
    word: "demagog",
    options: ["saklig debattör", "tystlåten iakttagare", "folkuppviglande talare", "neutral moderator", "försiktig rådgivare"],
    correct: 2,
    explanation: "En demagog vinner stöd genom att spela på känslor snarare än fakta.",
    source: "egen (HP-typ)",
  },
  {
    id: "despot",
    word: "despot",
    options: ["vald representant", "rådgivande ämbetsman", "opartisk domare", "godtycklig envåldshärskare", "ödmjuk tjänare"],
    correct: 3,
    explanation: "En despot styr med absolut och ofta grym makt.",
    source: "egen (HP-typ)",
  },
  {
    id: "diffus",
    word: "diffus",
    options: ["skarpt avgränsad", "exakt definierad", "lätt att förstå", "tydligt formulerad", "otydlig och svårurskiljbar"],
    correct: 4,
    explanation: "Diffus betyder oklar i sina konturer eller sitt innehåll.",
    source: "egen (HP-typ)",
  },
  {
    id: "diskret",
    word: "diskret",
    options: ["återhållsam och omärklig", "högljudd", "iögonfallande", "påträngande", "skrytsam"],
    correct: 0,
    explanation: "Diskret betyder att uppträda utan att dra till sig onödig uppmärksamhet.",
    source: "egen (HP-typ)",
  },
  {
    id: "dogmatisk",
    word: "dogmatisk",
    options: ["öppen för omprövning", "orubbligt fast vid sina åsikter", "ödmjuk i sitt ställningstagande", "tveksam och sökande", "kompromissvillig"],
    correct: 1,
    explanation: "Dogmatisk betyder att hålla fast vid en lära utan att ifrågasätta den.",
    source: "egen (HP-typ)",
  },
  {
    id: "dubiös",
    word: "dubiös",
    options: ["oantastlig", "väldokumenterad", "tvivelaktig", "trovärdig", "erkänd"],
    correct: 2,
    explanation: "Dubiös betyder osäker till sin karaktär, med tveksam trovärdighet.",
    source: "egen (HP-typ)",
  },
  {
    id: "eklektisk",
    word: "eklektisk",
    options: ["renodlad i en enda stil", "strikt regelbunden", "helt originell", "sammansatt av olika stilar", "enhetlig i uttrycket"],
    correct: 3,
    explanation: "Eklektisk beskriver något som hämtar element från många olika håll.",
    source: "egen (HP-typ)",
  },
  {
    id: "emfas",
    word: "emfas",
    options: ["tystnad", "tvekan", "återhållsamhet", "avledning", "kraftig betoning"],
    correct: 4,
    explanation: "Emfas läggs på det man vill framhäva som särskilt viktigt.",
    source: "egen (HP-typ)",
  },
  {
    id: "empirisk",
    word: "empirisk",
    options: ["grundad på erfarenhet", "grundad på tro", "grundad på antaganden", "grundad på tradition", "grundad på känslor"],
    correct: 0,
    explanation: "Empirisk kunskap bygger på observation och undersökning, inte enbart teori.",
    source: "egen (HP-typ)",
  },
  {
    id: "enfaldig",
    word: "enfaldig",
    options: ["skarpsinnig", "godtroget okritisk", "misstänksam", "beräknande", "analytisk"],
    correct: 1,
    explanation: "Enfaldig betyder naiv och lättlurad.",
    source: "egen (HP-typ)",
  },
  {
    id: "entydig",
    word: "entydig",
    options: ["mångtydig", "vag", "helt klar och otvetydig", "motsägelsefull", "svårtolkad"],
    correct: 2,
    explanation: "Entydig betyder att bara kunna tolkas på ett sätt.",
    source: "egen (HP-typ)",
  },
  {
    id: "epok",
    word: "epok",
    options: ["kortvarigt tillfälle", "enstaka händelse", "framtida möjlighet", "historisk tidsperiod", "personlig minnesbild"],
    correct: 3,
    explanation: "En epok är ett längre, sammanhängande skede i historien.",
    source: "egen (HP-typ)",
  },
  {
    id: "esoterisk",
    word: "esoterisk",
    options: ["allmänt tillgänglig", "lättfattlig", "populär", "förenklad", "begriplig endast för invigda"],
    correct: 4,
    explanation: "Esoterisk kunskap är förbehållen en liten, invigd krets.",
    source: "egen (HP-typ)",
  },
  {
    id: "eufori",
    word: "eufori",
    options: ["stark lyckokänsla", "djup sorg", "stilla ro", "kall likgiltighet", "svag besvikelse"],
    correct: 0,
    explanation: "Eufori är en intensiv känsla av lycka och upprymdhet.",
    source: "egen (HP-typ)",
  },
  {
    id: "excentrisk",
    word: "excentrisk",
    options: ["konventionell", "avvikande från det vanliga", "förutsägbar", "återhållsam", "anpasslig"],
    correct: 1,
    explanation: "Excentrisk betyder originell på ett udda, iögonfallande sätt.",
    source: "egen (HP-typ)",
  },
  {
    id: "exkludera",
    word: "exkludera",
    options: ["inkludera", "belöna", "utesluta", "uppmuntra", "framhäva"],
    correct: 2,
    explanation: "Att exkludera någon är att medvetet hålla dem utanför.",
    source: "egen (HP-typ)",
  },
  {
    id: "exponera",
    word: "exponera",
    options: ["dölja fullständigt", "skydda mot upptäckt", "underlätta för", "utsätta för insyn", "avleda från"],
    correct: 3,
    explanation: "Att exponera något är att göra det synligt eller sårbart.",
    source: "egen (HP-typ)",
  },
  {
    id: "extrovert",
    word: "extrovert",
    options: ["inåtvänd", "reserverad", "blyg", "tillbakadragen", "utåtriktad i sitt sätt"],
    correct: 4,
    explanation: "Extrovert betyder att söka energi i sociala sammanhang.",
    source: "egen (HP-typ)",
  },
  {
    id: "fanatisk",
    word: "fanatisk",
    options: ["överdrivet hängiven", "likgiltig", "måttfull", "tveksam", "avmätt"],
    correct: 0,
    explanation: "Fanatisk betyder blint och okritiskt hängiven en sak eller idé.",
    source: "egen (HP-typ)",
  },
  {
    id: "farsartad",
    word: "farsartad",
    options: ["stillsam och ordnad", "löjeväckande kaotisk", "allvarlig och högtidlig", "sorglig och tragisk", "sober och saklig"],
    correct: 1,
    explanation: "Farsartad beskriver en händelse som utvecklas till ett skämtsamt kaos.",
    source: "egen (HP-typ)",
  },
  {
    id: "finurlig",
    word: "finurlig",
    options: ["klumpig", "tröghjärnad", "påhittigt smart", "ointresserad", "slarvig"],
    correct: 2,
    explanation: "Finurlig betyder uppfinningsrik och listig på ett sympatiskt sätt.",
    source: "egen (HP-typ)",
  },
  {
    id: "flegmatisk",
    word: "flegmatisk",
    options: ["hetlevrad", "lättrörd", "impulsiv", "trögt oberörd", "nervös"],
    correct: 3,
    explanation: "Flegmatisk betyder lugn och svårrubbad till sitt temperament.",
    source: "egen (HP-typ)",
  },
  {
    id: "flertydig",
    word: "flertydig",
    options: ["entydig", "tydlig", "exakt", "otvetydig", "möjlig att tolka på olika sätt"],
    correct: 4,
    explanation: "Flertydig betyder att ha mer än en möjlig tolkning.",
    source: "egen (HP-typ)",
  },
  {
    id: "formidabel",
    word: "formidabel",
    options: ["imponerande stor", "obetydlig", "blygsam", "anspråkslös", "försumbar"],
    correct: 0,
    explanation: "Formidabel betyder mäktig och respektingivande i sin storlek.",
    source: "egen (HP-typ)",
  },
  {
    id: "frivol",
    word: "frivol",
    options: ["strängt allvarlig", "lättsinnigt lekfull", "djupt religiös", "överdrivet formell", "återhållsam"],
    correct: 1,
    explanation: "Frivol betyder lekfullt oanständig eller ytligt underhållande.",
    source: "egen (HP-typ)",
  },
  {
    id: "frenetisk",
    word: "frenetisk",
    options: ["stilla och lugn", "avslappnad", "febrilt intensiv", "trög och seg", "sansad"],
    correct: 2,
    explanation: "Frenetisk betyder hetsig och nästan upphetsad i sin aktivitet.",
    source: "egen (HP-typ)",
  },
  {
    id: "föråldrad",
    word: "föråldrad",
    options: ["nyskapande", "aktuell", "framtidsinriktad", "omodern", "modern"],
    correct: 3,
    explanation: "Föråldrad betyder att inte längre vara tidsenlig.",
    source: "egen (HP-typ)",
  },
  {
    id: "förnimma",
    word: "förnimma",
    options: ["helt bortse från", "tydligt bevisa", "aktivt förneka", "högljutt hävda", "vagt uppfatta"],
    correct: 4,
    explanation: "Att förnimma något är att ana eller känna det utan att helt kunna sätta ord på det.",
    source: "egen (HP-typ)",
  },
  {
    id: "förhärskande",
    word: "förhärskande",
    options: ["dominerande", "undanskymd", "sällsynt", "underordnad", "marginell"],
    correct: 0,
    explanation: "Förhärskande betyder rådande och mest utbredd.",
    source: "egen (HP-typ)",
  },
  {
    id: "förslagen",
    word: "förslagen",
    options: ["godtrogen", "listigt beräknande", "ärlig", "rättfram", "naiv"],
    correct: 1,
    explanation: "Förslagen betyder slug och skicklig på att lura andra.",
    source: "egen (HP-typ)",
  },
  {
    id: "försumlig",
    word: "försumlig",
    options: ["ytterst noggrann", "plikttrogen", "vårdslöst nonchalant", "omsorgsfull", "pålitlig"],
    correct: 2,
    explanation: "Försumlig betyder att inte sköta sina skyldigheter.",
    source: "egen (HP-typ)",
  },
  {
    id: "förtida",
    word: "förtida",
    options: ["försenad", "planenlig", "återkommande", "tidigare än väntat", "uppskjuten"],
    correct: 3,
    explanation: "Förtida betyder att inträffa innan den normala tidpunkten.",
    source: "egen (HP-typ)",
  },
  {
    id: "förträfflig",
    word: "förträfflig",
    options: ["medioker", "undermålig", "bristfällig", "otillräcklig", "utomordentligt god"],
    correct: 4,
    explanation: "Förträfflig betyder utmärkt, av högsta kvalitet.",
    source: "egen (HP-typ)",
  },
  {
    id: "genant",
    word: "genant",
    options: ["pinsamt", "hedrande", "smickrande", "upplyftande", "stärkande"],
    correct: 0,
    explanation: "Genant betyder att väcka förlägenhet eller skam.",
    source: "egen (HP-typ)",
  },
  {
    id: "genuin",
    word: "genuin",
    options: ["konstlad", "äkta", "iscensatt", "efterapad", "förställd"],
    correct: 1,
    explanation: "Genuin betyder verkligt äkta, utan förställning.",
    source: "egen (HP-typ)",
  },
  {
    id: "gles",
    word: "gles",
    options: ["tät", "kompakt", "glest fördelad", "sammanpackad", "koncentrerad"],
    correct: 2,
    explanation: "Gles betyder att ha stora mellanrum mellan delarna.",
    source: "egen (HP-typ)",
  },
  {
    id: "grandios",
    word: "grandios",
    options: ["blygsam", "anspråkslös", "diskret", "storslaget överdriven", "återhållsam"],
    correct: 3,
    explanation: "Grandios betyder praktfull, ofta i överkant.",
    source: "egen (HP-typ)",
  },
  {
    id: "gäckande",
    word: "gäckande",
    options: ["lättillgänglig", "uppenbar", "påträngande", "rättfram", "svårfångad och lurande"],
    correct: 4,
    explanation: "Gäckande betyder att undflyende reta eller lura.",
    source: "egen (HP-typ)",
  },
  {
    id: "hegemoni",
    word: "hegemoni",
    options: ["överhögt inflytande", "jämbördigt samarbete", "underordnad ställning", "tillfällig allians", "öppen konkurrens"],
    correct: 0,
    explanation: "Hegemoni är en dominerande maktställning över andra.",
    source: "egen (HP-typ)",
  },
  {
    id: "hierarki",
    word: "hierarki",
    options: ["slumpmässig samling", "rangordnad struktur", "jämlik gemenskap", "informellt nätverk", "tillfällig grupp"],
    correct: 1,
    explanation: "Hierarki är ett system där delar rangordnas efter status eller makt.",
    source: "egen (HP-typ)",
  },
  {
    id: "hypotetisk",
    word: "hypotetisk",
    options: ["fastställd genom bevis", "allmänt vedertagen", "antagen men obevisad", "empiriskt styrkt", "obestridlig"],
    correct: 2,
    explanation: "Hypotetisk betyder tänkt eller antagen, inte nödvändigtvis sann.",
    source: "egen (HP-typ)",
  },
  {
    id: "hämndlysten",
    word: "hämndlysten",
    options: ["förlåtande", "likgiltig", "fridfull", "revanschsugen", "överseende"],
    correct: 3,
    explanation: "Hämndlysten betyder att vilja vedergälla en oförrätt.",
    source: "egen (HP-typ)",
  },
  {
    id: "härdad",
    word: "härdad",
    options: ["skör och känslig", "orörd och oprövad", "mjuk och foglig", "lättpåverkad", "prövad och tålig"],
    correct: 4,
    explanation: "Härdad betyder att ha blivit tålig genom svåra erfarenheter.",
    source: "egen (HP-typ)",
  },
  {
    id: "idog",
    word: "idog",
    options: ["flitig och uthållig", "lat och ointresserad", "slarvig och ostrukturerad", "nyckfull", "obeslutsam"],
    correct: 0,
    explanation: "Idog betyder att arbeta träget och uthålligt.",
    source: "egen (HP-typ)",
  },
  {
    id: "ignorant",
    word: "ignorant",
    options: ["välinformerad", "okunnig", "kunnig", "insatt", "beläst"],
    correct: 1,
    explanation: "Ignorant betyder att sakna kunskap om något, ofta medvetet.",
    source: "egen (HP-typ)",
  },
  {
    id: "illusorisk",
    word: "illusorisk",
    options: ["konkret och verklig", "bevisligen sann", "skenbar men overklig", "väl underbyggd", "påtaglig"],
    correct: 2,
    explanation: "Illusorisk betyder att bara verka vara sant, en synvilla.",
    source: "egen (HP-typ)",
  },
  {
    id: "immun",
    word: "immun",
    options: ["mottaglig", "känslig", "sårbar", "oemottaglig för påverkan", "påverkbar"],
    correct: 3,
    explanation: "Immun betyder skyddad från att påverkas, t.ex. av sjukdom eller kritik.",
    source: "egen (HP-typ)",
  },
  {
    id: "impulsiv",
    word: "impulsiv",
    options: ["genomtänkt", "försiktig", "kalkylerande", "återhållsam", "handlande utan eftertanke"],
    correct: 4,
    explanation: "Impulsiv betyder att handla plötsligt, utan att först fundera.",
    source: "egen (HP-typ)",
  },
  {
    id: "inbiten",
    word: "inbiten",
    options: ["djupt rotad i en vana", "nyfrälst", "tveksam", "ambivalent", "tillfällig"],
    correct: 0,
    explanation: "Inbiten betyder starkt fastvuxen i en vana eller övertygelse.",
    source: "egen (HP-typ)",
  },
  {
    id: "indignerad",
    word: "indignerad",
    options: ["belåten", "upprört förnärmad", "likgiltig", "road", "avspänd"],
    correct: 1,
    explanation: "Indignerad betyder att känna moralisk upprördhet över något orätt.",
    source: "egen (HP-typ)",
  },
  {
    id: "infam",
    word: "infam",
    options: ["hedervärd", "aktningsvärd", "avskyvärt skändlig", "oantastlig", "berömd"],
    correct: 2,
    explanation: "Infam betyder ökänd för sin skamlöshet.",
    source: "egen (HP-typ)",
  },
  {
    id: "ingrodd",
    word: "ingrodd",
    options: ["nyligen uppkommen", "tillfällig", "lättföränderlig", "djupt inrotad", "ytlig"],
    correct: 3,
    explanation: "Ingrodd betyder att ha funnits så länge att det blivit svårt att ändra.",
    source: "egen (HP-typ)",
  },
  {
    id: "inkonsekvent",
    word: "inkonsekvent",
    options: ["följdriktig", "konsekvent", "systematisk", "förutsägbar", "motsägelsefullt oregelbunden"],
    correct: 4,
    explanation: "Inkonsekvent betyder att inte handla enligt samma princip varje gång.",
    source: "egen (HP-typ)",
  },
  {
    id: "insinuera",
    word: "insinuera",
    options: ["antyda något negativt", "öppet påstå", "tydligt bevisa", "direkt fråga", "uttryckligen förneka"],
    correct: 0,
    explanation: "Att insinuera är att antyda något, ofta illvilligt, utan att säga det rakt ut.",
    source: "egen (HP-typ)",
  },
  {
    id: "introvert",
    word: "introvert",
    options: ["utåtriktad", "inåtvänd i sitt sätt", "social", "pratsam", "sällskaplig"],
    correct: 1,
    explanation: "Introvert betyder att hämta energi genom ensamhet snarare än socialt umgänge.",
    source: "egen (HP-typ)",
  },
  {
    id: "kapitulera",
    word: "kapitulera",
    options: ["fortsätta kämpa", "segra", "ge upp motståndet", "förhandla från styrka", "avvisa villkoren"],
    correct: 2,
    explanation: "Att kapitulera är att erkänna sig besegrad och sluta strida.",
    source: "egen (HP-typ)",
  },
  {
    id: "karg",
    word: "karg",
    options: ["frodig", "bördig", "riklig", "torftig och ogästvänlig", "lummig"],
    correct: 3,
    explanation: "Karg beskriver en miljö som ger lite, ofta stenig och naturfattig.",
    source: "egen (HP-typ)",
  },
  {
    id: "karismatisk",
    word: "karismatisk",
    options: ["färglös och osynlig", "blyg och tillbakadragen", "avvisande och kylig", "trist och enformig", "utstrålande stark personlig dragningskraft"],
    correct: 4,
    explanation: "Karismatisk betyder att naturligt fängsla och entusiasmera andra.",
    source: "egen (HP-typ)",
  },
  {
    id: "katalysator",
    word: "katalysator",
    options: ["påskyndande faktor", "bromsande hinder", "slumpmässig händelse", "oberoende variabel", "stabiliserande kraft"],
    correct: 0,
    explanation: "En katalysator sätter fart på en process utan att själv förbrukas.",
    source: "egen (HP-typ)",
  },
  {
    id: "klaustrofobisk",
    word: "klaustrofobisk",
    options: ["öppet rymlig", "instängt kvävande", "luftig och fri", "vidsträckt", "obegränsad"],
    correct: 1,
    explanation: "Klaustrofobisk beskriver en känsla av att vara instängd och trängd.",
    source: "egen (HP-typ)",
  },
  {
    id: "koherent",
    word: "koherent",
    options: ["osammanhängande", "spretig", "sammanhängande logisk", "motsägelsefull", "splittrad"],
    correct: 2,
    explanation: "Koherent betyder att delarna hänger ihop på ett begripligt sätt.",
    source: "egen (HP-typ)",
  },
  {
    id: "kompatibel",
    word: "kompatibel",
    options: ["oförenlig", "motstridig", "ovillig att samverka", "förenlig med annat", "svårförenlig"],
    correct: 3,
    explanation: "Kompatibel betyder att kunna fungera tillsammans med något annat.",
    source: "egen (HP-typ)",
  },
  {
    id: "konform",
    word: "konform",
    options: ["avvikande", "originell", "uppstudsig", "självständig", "anpassad efter normen"],
    correct: 4,
    explanation: "Konform betyder att rätta sig efter det förväntade.",
    source: "egen (HP-typ)",
  },
  {
    id: "kontraproduktiv",
    word: "kontraproduktiv",
    options: ["motverkande sitt eget syfte", "gynnsam för målet", "effektiv", "ändamålsenlig", "framgångsrik"],
    correct: 0,
    explanation: "Kontraproduktiv betyder att en åtgärd får motsatt effekt mot vad som avsågs.",
    source: "egen (HP-typ)",
  },
  {
    id: "konventionell",
    word: "konventionell",
    options: ["nyskapande", "traditionell och sedvanlig", "excentrisk", "radikal", "banbrytande"],
    correct: 1,
    explanation: "Konventionell betyder att följa det vedertagna och förväntade.",
    source: "egen (HP-typ)",
  },
  {
    id: "konstlad",
    word: "konstlad",
    options: ["äkta", "naturlig", "onaturligt tillgjord", "spontan", "genuin"],
    correct: 2,
    explanation: "Konstlad betyder framtvingad eller tillgjord snarare än äkta.",
    source: "egen (HP-typ)",
  },
  {
    id: "korpulent",
    word: "korpulent",
    options: ["mager", "spenslig", "smärt", "kraftigt bastant", "vältränad"],
    correct: 3,
    explanation: "Korpulent betyder tjock och skrymmande till kroppshyddan.",
    source: "egen (HP-typ)",
  },
  {
    id: "kroniskt",
    word: "kroniskt",
    options: ["tillfälligt", "akut och kortvarigt", "sporadiskt", "övergående", "ihållande under lång tid"],
    correct: 4,
    explanation: "Kroniskt betyder långvarigt återkommande, t.ex. om en sjukdom.",
    source: "egen (HP-typ)",
  },
  {
    id: "labil",
    word: "labil",
    options: ["instabil och lättpåverkad", "stabil", "fast", "orubblig", "beständig"],
    correct: 0,
    explanation: "Labil betyder att lätt växla mellan tillstånd, ofta känslomässigt.",
    source: "egen (HP-typ)",
  },
  {
    id: "lakonisk",
    word: "lakonisk",
    options: ["utförlig", "kortfattat sparsmakad", "svamlig", "omständlig", "pratsam"],
    correct: 1,
    explanation: "Lakonisk betyder kortfattad och fåordig.",
    source: "egen (HP-typ)",
  },
  {
    id: "lugubert",
    word: "lugubert",
    options: ["upplyftande", "gladlynt", "dyster och olycksbådande", "hoppfull", "muntert"],
    correct: 2,
    explanation: "Lugubert beskriver en dyster, hotfull stämning.",
    source: "egen (HP-typ)",
  },
  {
    id: "lynnig",
    word: "lynnig",
    options: ["stabilt jämnmodig", "förutsägbar", "orubbligt lugn", "nyckfullt humörsvängande", "konsekvent"],
    correct: 3,
    explanation: "Lynnig betyder att växla mellan olika humör utan förvarning.",
    source: "egen (HP-typ)",
  },
  {
    id: "malplacerad",
    word: "malplacerad",
    options: ["väl anpassad", "passande", "hemmahörande", "korrekt situerad", "olämpligt placerad"],
    correct: 4,
    explanation: "Malplacerad betyder att inte höra hemma i sammanhanget.",
    source: "egen (HP-typ)",
  },
  {
    id: "manisk",
    word: "manisk",
    options: ["överdrivet upprymt intensiv", "dämpad och lugn", "loj och trög", "avspänd", "stillsam"],
    correct: 0,
    explanation: "Manisk betyder överdrivet och rastlöst upprymd, ibland i kliniskt bemärkelse.",
    source: "egen (HP-typ)",
  },
  {
    id: "marginell",
    word: "marginell",
    options: ["avgörande", "obetydligt liten", "betydande", "central", "dominerande"],
    correct: 1,
    explanation: "Marginell betyder att ha liten påverkan eller betydelse.",
    source: "egen (HP-typ)",
  },
  {
    id: "melankolisk",
    word: "melankolisk",
    options: ["uppsluppen", "livfull", "vemodigt nedstämd", "glättig", "jovialisk"],
    correct: 2,
    explanation: "Melankolisk betyder tyngd av ett stilla vemod.",
    source: "egen (HP-typ)",
  },
  {
    id: "metodisk",
    word: "metodisk",
    options: ["planlös", "spretig", "kaotisk", "systematiskt ordnad", "godtycklig"],
    correct: 3,
    explanation: "Metodisk betyder att arbeta strukturerat efter en bestämd ordning.",
    source: "egen (HP-typ)",
  },
  {
    id: "militant",
    word: "militant",
    options: ["fredlig och försonlig", "eftergiven", "passiv", "tillbakadragen", "stridslystet radikal"],
    correct: 4,
    explanation: "Militant betyder beredd att använda kraftfulla, ofta konfrontativa medel.",
    source: "egen (HP-typ)",
  },
  {
    id: "minutiös",
    word: "minutiös",
    options: ["ytterst detaljerad", "översiktlig", "grovhuggen", "slarvig", "flyktig"],
    correct: 0,
    explanation: "Minutiös betyder extremt noggrann in i minsta detalj.",
    source: "egen (HP-typ)",
  },
  {
    id: "missvisande",
    word: "missvisande",
    options: ["rättvisande", "vilseledande i sitt intryck", "korrekt", "träffsäker", "klargörande"],
    correct: 1,
    explanation: "Missvisande betyder att ge en felaktig eller skev bild.",
    source: "egen (HP-typ)",
  },
  {
    id: "monoton",
    word: "monoton",
    options: ["omväxlande", "varierad", "enformigt oföränderlig", "dynamisk", "nyanserad"],
    correct: 2,
    explanation: "Monoton betyder tråkigt oföränderlig, utan variation.",
    source: "egen (HP-typ)",
  },
  {
    id: "mystifierande",
    word: "mystifierande",
    options: ["klargörande", "uppenbar", "självförklarande", "förbryllande gåtfull", "entydig"],
    correct: 3,
    explanation: "Mystifierande betyder att göra något oklart eller svårgenomträngligt.",
    source: "egen (HP-typ)",
  },
  {
    id: "narcissistisk",
    word: "narcissistisk",
    options: ["osjälvisk", "blygsam", "anspråkslös", "självutplånande", "överdrivet självupptagen"],
    correct: 4,
    explanation: "Narcissistisk betyder att ha en överdriven bild av sin egen betydelse.",
    source: "egen (HP-typ)",
  },
  {
    id: "nonchalant",
    word: "nonchalant",
    options: ["likgiltigt oberörd", "engagerad", "noggrann", "omtänksam", "plikttrogen"],
    correct: 0,
    explanation: "Nonchalant betyder att bete sig obekymrat, utan större hänsyn.",
    source: "egen (HP-typ)",
  },
  {
    id: "normativ",
    word: "normativ",
    options: ["beskrivande hur något faktiskt är", "föreskrivande hur något bör vara", "neutralt konstaterande", "rent statistisk", "objektivt mätande"],
    correct: 1,
    explanation: "Normativ betyder att ange en norm eller ett önskvärt tillstånd.",
    source: "egen (HP-typ)",
  },
  {
    id: "notorisk",
    word: "notorisk",
    options: ["okänd", "anonym", "allmänt känd för något negativt", "obemärkt", "diskret"],
    correct: 2,
    explanation: "Notorisk betyder ökänd, känd för en återkommande dålig egenskap.",
    source: "egen (HP-typ)",
  },
  {
    id: "obscen",
    word: "obscen",
    options: ["oskyldig", "anständig", "återhållsam", "stötande oanständig", "kysk"],
    correct: 3,
    explanation: "Obscen betyder grovt anstötlig, ofta sexuellt.",
    source: "egen (HP-typ)",
  },
  {
    id: "odiskutabel",
    word: "odiskutabel",
    options: ["tveksam", "diskutabel", "omtvistad", "osäker", "bortom all tvekan"],
    correct: 4,
    explanation: "Odiskutabel betyder så självklar att den inte kan ifrågasättas.",
    source: "egen (HP-typ)",
  },
  {
    id: "ofattbar",
    word: "ofattbar",
    options: ["omöjlig att förstå", "självklar", "lättbegriplig", "uppenbar", "logisk"],
    correct: 0,
    explanation: "Ofattbar betyder att gå bortom vad förnuftet kan greppa.",
    source: "egen (HP-typ)",
  },
  {
    id: "ohämmad",
    word: "ohämmad",
    options: ["återhållsam", "utan spärrar eller återhållsamhet", "blyg", "reserverad", "tillbakadragen"],
    correct: 1,
    explanation: "Ohämmad betyder att agera fritt utan hänsyn till hämningar.",
    source: "egen (HP-typ)",
  },
  {
    id: "okonventionell",
    word: "okonventionell",
    options: ["traditionell", "konventionell", "avvikande från det vedertagna", "sedvanlig", "vanlig"],
    correct: 2,
    explanation: "Okonventionell betyder att göra saker på ett ovanligt, oväntat sätt.",
    source: "egen (HP-typ)",
  },
  {
    id: "opportunistisk",
    word: "opportunistisk",
    options: ["principfast", "idealistisk", "osjälvisk", "tillfällighetsutnyttjande", "konsekvent"],
    correct: 3,
    explanation: "Opportunistisk betyder att utnyttja tillfällen utan hänsyn till principer.",
    source: "egen (HP-typ)",
  },
  {
    id: "oräddhet",
    word: "oräddhet",
    options: ["stark oro", "tveksamhet", "vaksamhet", "misstänksamhet", "avsaknad av fruktan"],
    correct: 4,
    explanation: "Oräddhet är förmågan att handla trots fara eller risk.",
    source: "egen (HP-typ)",
  },
  {
    id: "oreflekterad",
    word: "oreflekterad",
    options: ["ogenomtänkt", "väl genomtänkt", "noga övervägd", "eftertänksam", "kalkylerad"],
    correct: 0,
    explanation: "Oreflekterad betyder att göra något utan att först tänka igenom det.",
    source: "egen (HP-typ)",
  },
  {
    id: "otyglad",
    word: "otyglad",
    options: ["strikt kontrollerad", "obehärskad och fri", "väl tillrättalagd", "disciplinerad", "återhållsam"],
    correct: 1,
    explanation: "Otyglad betyder att inte hålla tillbaka en kraft eller känsla.",
    source: "egen (HP-typ)",
  },
  {
    id: "paradox",
    word: "paradox",
    options: ["självklar sanning", "logisk följd", "skenbar motsägelse", "tydlig bekräftelse", "enkel förklaring"],
    correct: 2,
    explanation: "En paradox verkar motsäga sig själv men kan ändå vara sann.",
    source: "egen (HP-typ)",
  },
  {
    id: "passiv",
    word: "passiv",
    options: ["handlingskraftig", "initiativrik", "drivande", "overksamt avvaktande", "aktiv"],
    correct: 3,
    explanation: "Passiv betyder att inte själv ta initiativ eller agera.",
    source: "egen (HP-typ)",
  },
  {
    id: "patetisk",
    word: "patetisk",
    options: ["imponerande", "respektingivande", "värdig", "sansad", "löjeväckande gripande"],
    correct: 4,
    explanation: "Patetisk beskriver något som väcker medlidande blandat med löje.",
    source: "egen (HP-typ)",
  },
  {
    id: "pedantisk",
    word: "pedantisk",
    options: ["överdrivet noggrann med detaljer", "slarvig", "översiktlig", "obekymrad", "nonchalant"],
    correct: 0,
    explanation: "Pedantisk betyder att fästa överdriven vikt vid formaliteter och småsaker.",
    source: "egen (HP-typ)",
  },
  {
    id: "perifer",
    word: "perifer",
    options: ["central", "belägen i utkanten", "avgörande", "grundläggande", "kärnfull"],
    correct: 1,
    explanation: "Perifer betyder att ligga vid sidan om det viktigaste.",
    source: "egen (HP-typ)",
  },
  {
    id: "plausibel",
    word: "plausibel",
    options: ["orimlig", "osannolik", "trovärdigt rimlig", "obegriplig", "orealistisk"],
    correct: 2,
    explanation: "Plausibel betyder att verka trolig och rimlig.",
    source: "egen (HP-typ)",
  },
  {
    id: "polariserad",
    word: "polariserad",
    options: ["enad", "samstämmig", "harmonisk", "uppdelad i motsatta läger", "sammanhållen"],
    correct: 3,
    explanation: "Polariserad betyder att åsikter dragit isär till skarpa motpoler.",
    source: "egen (HP-typ)",
  },
  {
    id: "precisera",
    word: "precisera",
    options: ["förvirra", "fördunkla", "generalisera", "komplicera", "göra mer exakt"],
    correct: 4,
    explanation: "Att precisera något är att göra det tydligare och mer exakt.",
    source: "egen (HP-typ)",
  },
  {
    id: "prekär",
    word: "prekär",
    options: ["vansklig och osäker", "trygg", "stabil", "riskfri", "förutsägbar"],
    correct: 0,
    explanation: "Prekär betyder att befinna sig i ett osäkert och känsligt läge.",
    source: "egen (HP-typ)",
  },
  {
    id: "promiskuös",
    word: "promiskuös",
    options: ["trogen", "obundet växlande i relationer", "monogam", "bunden", "lojal"],
    correct: 1,
    explanation: "Promiskuös beskriver ett mönster av många, lösa relationer.",
    source: "egen (HP-typ)",
  },
  {
    id: "provokativ",
    word: "provokativ",
    options: ["försonande", "harmlös", "medvetet utmanande", "blygsam", "tillbakadragen"],
    correct: 2,
    explanation: "Provokativ betyder avsedd att reta upp eller utmana.",
    source: "egen (HP-typ)",
  },
  {
    id: "pueril",
    word: "pueril",
    options: ["mogen", "vuxen i sitt sätt", "sansad", "barnsligt omogen", "ansvarsfull"],
    correct: 3,
    explanation: "Pueril betyder att uppföra sig barnsligt trots vuxen ålder.",
    source: "egen (HP-typ)",
  },
  {
    id: "rationell",
    word: "rationell",
    options: ["irrationell", "impulsiv", "känslostyrd", "godtycklig", "förnuftsstyrd"],
    correct: 4,
    explanation: "Rationell betyder att handla utifrån logik och förnuft.",
    source: "egen (HP-typ)",
  },
  {
    id: "reciprok",
    word: "reciprok",
    options: ["ömsesidig", "ensidig", "obalanserad", "envägsriktad", "orättvis"],
    correct: 0,
    explanation: "Reciprok betyder att något gäller lika åt båda håll.",
    source: "egen (HP-typ)",
  },
  {
    id: "reserverad",
    word: "reserverad",
    options: ["öppenhjärtig", "avvaktande tillbakadragen", "utåtriktad", "pratsam", "hjärtlig"],
    correct: 1,
    explanation: "Reserverad betyder försiktigt återhållsam i kontakt med andra.",
    source: "egen (HP-typ)",
  },
  {
    id: "resignerad",
    word: "resignerad",
    options: ["kämpaglad", "hoppfull", "uppgivet accepterande", "beslutsam", "stridslysten"],
    correct: 2,
    explanation: "Resignerad betyder att ha gett upp hoppet om förändring.",
    source: "egen (HP-typ)",
  },
  {
    id: "saklig",
    word: "saklig",
    options: ["subjektiv", "vinklad", "känslostyrd", "objektivt korrekt", "partisk"],
    correct: 3,
    explanation: "Saklig betyder att hålla sig till fakta utan personliga infärgningar.",
    source: "egen (HP-typ)",
  },
  {
    id: "skeptisk",
    word: "skeptisk",
    options: ["godtrogen", "lättlurad", "naiv", "okritisk", "tvivlande kritisk"],
    correct: 4,
    explanation: "Skeptisk betyder att ifrågasätta och kräva bevis.",
    source: "egen (HP-typ)",
  },
  {
    id: "solidarisk",
    word: "solidarisk",
    options: ["sammanhållet stödjande", "egoistisk", "likgiltig", "konkurrerande", "splittrande"],
    correct: 0,
    explanation: "Solidarisk betyder att stå upp för och stödja andra i en gemenskap.",
    source: "egen (HP-typ)",
  },
  {
    id: "sporadisk",
    word: "sporadisk",
    options: ["ständigt pågående", "oregelbundet återkommande", "regelbunden", "kontinuerlig", "frekvent"],
    correct: 1,
    explanation: "Sporadisk betyder att inträffa då och då, utan fast mönster.",
    source: "egen (HP-typ)",
  },
  {
    id: "stagnerad",
    word: "stagnerad",
    options: ["blomstrande", "snabbt växande", "stillastående utan utveckling", "dynamisk", "framåtsträvande"],
    correct: 2,
    explanation: "Stagnerad betyder att ha slutat utvecklas eller växa.",
    source: "egen (HP-typ)",
  },
  {
    id: "subjektiv",
    word: "subjektiv",
    options: ["objektiv", "opartisk", "saklig", "personligt färgad", "neutral"],
    correct: 3,
    explanation: "Subjektiv betyder präglad av den egna uppfattningen snarare än fakta.",
    source: "egen (HP-typ)",
  },
  {
    id: "subtil",
    word: "subtil",
    options: ["grov", "påträngande", "uppenbar", "klumpig", "förfinat diskret"],
    correct: 4,
    explanation: "Subtil betyder finstämt och svårupptäckt.",
    source: "egen (HP-typ)",
  },
  {
    id: "suverän",
    word: "suverän",
    options: ["överlägset skicklig", "klumpig", "osäker", "medioker", "bristfällig"],
    correct: 0,
    explanation: "Suverän betyder att behärska något med stor säkerhet och auktoritet.",
    source: "egen (HP-typ)",
  },
  {
    id: "symbios",
    word: "symbios",
    options: ["ensidigt utnyttjande", "ömsesidigt givande samlevnad", "fientlig konkurrens", "isolerad existens", "kortvarig konflikt"],
    correct: 1,
    explanation: "Symbios är ett samspel där båda parter drar nytta av varandra.",
    source: "egen (HP-typ)",
  },
  {
    id: "temperamentsfull",
    word: "temperamentsfull",
    options: ["känslokall", "avmätt", "starkt känslostyrd", "oberörd", "likgiltig"],
    correct: 2,
    explanation: "Temperamentsfull betyder att ha starka, lättväckta känsloreaktioner.",
    source: "egen (HP-typ)",
  },
  {
    id: "tvetydig",
    word: "tvetydig",
    options: ["entydig", "otvetydig", "klar", "möjlig att tolka på olika sätt", "exakt"],
    correct: 3,
    explanation: "Tvetydig betyder att ha mer än en möjlig innebörd.",
    source: "egen (HP-typ)",
  },
  {
    id: "unison",
    word: "unison",
    options: ["splittrad", "oenig", "motsägelsefull", "spretig", "helt samstämmig"],
    correct: 4,
    explanation: "Unison betyder att alla är fullständigt överens.",
    source: "egen (HP-typ)",
  },
];
